/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ForceKeepAliveMessage : Force keep alive websocket messages. The data is the timeout in seconds after which the server considers the connection lost; clients are expected to answer with a KeepAlive message and to keep sending one at least every half of that timeout.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForceKeepAliveMessage {
    /// Gets or sets the data.
    #[serde(rename = "Data", skip_serializing_if = "Option::is_none")]
    pub data: Option<i32>,
    /// Gets or sets the message id.
    #[serde(rename = "MessageId", skip_serializing_if = "Option::is_none")]
    pub message_id: Option<uuid::Uuid>,
    /// The different kinds of messages that are used in the WebSocket api.
    #[serde(rename = "MessageType", skip_serializing_if = "Option::is_none")]
    pub message_type: Option<models::SessionMessageType>,
}

impl ForceKeepAliveMessage {
    /// Force keep alive websocket messages. The data is the timeout in seconds after which the server considers the connection lost; clients are expected to answer with a KeepAlive message and to keep sending one at least every half of that timeout.
    pub fn new() -> ForceKeepAliveMessage {
        ForceKeepAliveMessage {
            data: None,
            message_id: None,
            message_type: None,
        }
    }
}

