[package]
name = "jellyfin-sdk-rs"
version = "0.1.0"
edition = "2024"
authors = ["leuchthelp"]
description = "jellyfin rust sdk"
readme = "README.md"
repository = "https://github.com/leuchthelp/jellyfin-sdk-rs"
license-file = "LICENSE"

[dependencies]
jellyfin-generated-client = { path = "generated-client" }
reqwest = { version = "0.13", features = ["json"] }
url = "2.5.8" 
bon = "3.9"
thiserror = "2.0.19"