/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use async_trait::async_trait;
use reqwest;
use std::sync::Arc;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};
use crate::apis::ContentType;

#[async_trait]
pub trait AudioApi: Send + Sync {

    /// GET /Audio/{itemId}/stream
    ///
    /// 
    async fn get_audio_stream(&self,  params: GetAudioStreamParams ) -> Result<std::path::PathBuf, Error<GetAudioStreamError>>;

    /// GET /Audio/{itemId}/stream.{container}
    ///
    /// 
    async fn get_audio_stream_by_container(&self,  params: GetAudioStreamByContainerParams ) -> Result<std::path::PathBuf, Error<GetAudioStreamByContainerError>>;

    /// GET /Audio/{itemId}/universal
    ///
    /// 
    async fn get_universal_audio_stream(&self,  params: GetUniversalAudioStreamParams ) -> Result<std::path::PathBuf, Error<GetUniversalAudioStreamError>>;

    /// HEAD /Audio/{itemId}/stream
    ///
    /// 
    async fn head_audio_stream(&self,  params: HeadAudioStreamParams ) -> Result<std::path::PathBuf, Error<HeadAudioStreamError>>;

    /// HEAD /Audio/{itemId}/stream.{container}
    ///
    /// 
    async fn head_audio_stream_by_container(&self,  params: HeadAudioStreamByContainerParams ) -> Result<std::path::PathBuf, Error<HeadAudioStreamByContainerError>>;

    /// HEAD /Audio/{itemId}/universal
    ///
    /// 
    async fn head_universal_audio_stream(&self,  params: HeadUniversalAudioStreamParams ) -> Result<std::path::PathBuf, Error<HeadUniversalAudioStreamError>>;
}

pub struct AudioApiClient {
    configuration: Arc<configuration::Configuration>
}

impl AudioApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}


/// struct for passing parameters to the method [`AudioApi::get_audio_stream`]
#[derive(Clone, Debug)]
pub struct GetAudioStreamParams {
    /// The item id.
    pub item_id: String,
    /// The audio container.
    pub container: Option<String>,
    /// Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false.
    pub r#static: Option<bool>,
    /// The streaming parameters.
    pub params: Option<String>,
    /// The tag.
    pub tag: Option<String>,
    /// Optional. The dlna device profile id to utilize.
    pub device_profile_id: Option<String>,
    /// The play session id.
    pub play_session_id: Option<String>,
    /// The segment container.
    pub segment_container: Option<String>,
    /// The segment length.
    pub segment_length: Option<i32>,
    /// The minimum number of segments.
    pub min_segments: Option<i32>,
    /// The media version id, if playing an alternate version.
    pub media_source_id: Option<String>,
    /// The device id of the client requesting. Used to stop encoding processes when needed.
    pub device_id: Option<String>,
    /// Optional. Specify an audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url's extension.
    pub audio_codec: Option<String>,
    /// Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true.
    pub enable_auto_stream_copy: Option<bool>,
    /// Whether or not to allow copying of the video stream url.
    pub allow_video_stream_copy: Option<bool>,
    /// Whether or not to allow copying of the audio stream url.
    pub allow_audio_stream_copy: Option<bool>,
    /// Optional. Specify a specific audio sample rate, e.g. 44100.
    pub audio_sample_rate: Option<i32>,
    /// Optional. The maximum audio bit depth.
    pub max_audio_bit_depth: Option<i32>,
    /// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
    pub audio_bit_rate: Option<i32>,
    /// Optional. Specify a specific number of audio channels to encode to, e.g. 2.
    pub audio_channels: Option<i32>,
    /// Optional. Specify a maximum number of audio channels to encode to, e.g. 2.
    pub max_audio_channels: Option<i32>,
    /// Optional. Specify a specific an encoder profile (varies by encoder), e.g. main, baseline, high.
    pub profile: Option<String>,
    /// Optional. Specify a level for the encoder profile (varies by encoder), e.g. 3, 3.1.
    pub level: Option<String>,
    /// Optional. A specific video framerate to encode to, e.g. 23.976. Generally this should be omitted unless the device has specific requirements.
    pub framerate: Option<f32>,
    /// Optional. A specific maximum video framerate to encode to, e.g. 23.976. Generally this should be omitted unless the device has specific requirements.
    pub max_framerate: Option<f32>,
    /// Whether or not to copy timestamps when transcoding with an offset. Defaults to false.
    pub copy_timestamps: Option<bool>,
    /// Optional. Specify a starting offset, in ticks. 1 tick = 10000 ms.
    pub start_time_ticks: Option<i64>,
    /// Optional. The fixed horizontal resolution of the encoded video.
    pub width: Option<i32>,
    /// Optional. The fixed vertical resolution of the encoded video.
    pub height: Option<i32>,
    /// Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults.
    pub video_bit_rate: Option<i32>,
    /// Optional. The index of the subtitle stream to use. If omitted no subtitles will be used.
    pub subtitle_stream_index: Option<i32>,
    /// Optional. Specify the subtitle delivery method.
    pub subtitle_method: Option<String>,
    /// Optional.
    pub max_ref_frames: Option<i32>,
    /// Optional. The maximum video bit depth.
    pub max_video_bit_depth: Option<i32>,
    /// Optional. Whether to require avc.
    pub require_avc: Option<bool>,
    /// Optional. Whether to deinterlace the video.
    pub de_interlace: Option<bool>,
    /// Optional. Whether to require a non anamorphic stream.
    pub require_non_anamorphic: Option<bool>,
    /// Optional. The maximum number of audio channels to transcode.
    pub transcoding_max_audio_channels: Option<i32>,
    /// Optional. The limit of how many cpu cores to use.
    pub cpu_core_limit: Option<i32>,
    /// The live stream id.
    pub live_stream_id: Option<String>,
    /// Optional. Whether to enable the MpegtsM2Ts mode.
    pub enable_mpegts_m2_ts_mode: Option<bool>,
    /// Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url's extension.
    pub video_codec: Option<String>,
    /// Optional. Specify a subtitle codec to encode to.
    pub subtitle_codec: Option<String>,
    /// Optional. The transcoding reason.
    pub transcode_reasons: Option<String>,
    /// Optional. The index of the audio stream to use. If omitted the first audio stream will be used.
    pub audio_stream_index: Option<i32>,
    /// Optional. The index of the video stream to use. If omitted the first video stream will be used.
    pub video_stream_index: Option<i32>,
    /// Optional. The MediaBrowser.Model.Dlna.EncodingContext.
    pub context: Option<String>,
    /// Optional. The streaming options.
    pub stream_options: Option<std::collections::HashMap<String, String>>,
    /// Optional. Whether to enable Audio Encoding.
    pub enable_audio_vbr_encoding: Option<bool>
}

/// struct for passing parameters to the method [`AudioApi::get_audio_stream_by_container`]
#[derive(Clone, Debug)]
pub struct GetAudioStreamByContainerParams {
    /// The item id.
    pub item_id: String,
    /// The audio container.
    pub container: String,
    /// Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false.
    pub r#static: Option<bool>,
    /// The streaming parameters.
    pub params: Option<String>,
    /// The tag.
    pub tag: Option<String>,
    /// Optional. The dlna device profile id to utilize.
    pub device_profile_id: Option<String>,
    /// The play session id.
    pub play_session_id: Option<String>,
    /// The segment container.
    pub segment_container: Option<String>,
    /// The segment length.
    pub segment_length: Option<i32>,
    /// The minimum number of segments.
    pub min_segments: Option<i32>,
    /// The media version id, if playing an alternate version.
    pub media_source_id: Option<String>,
    /// The device id of the client requesting. Used to stop encoding processes when needed.
    pub device_id: Option<String>,
    /// Optional. Specify an audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url's extension.
    pub audio_codec: Option<String>,
    /// Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true.
    pub enable_auto_stream_copy: Option<bool>,
    /// Whether or not to allow copying of the video stream url.
    pub allow_video_stream_copy: Option<bool>,
    /// Whether or not to allow copying of the audio stream url.
    pub allow_audio_stream_copy: Option<bool>,
    /// Optional. Specify a specific audio sample rate, e.g. 44100.
    pub audio_sample_rate: Option<i32>,
    /// Optional. The maximum audio bit depth.
    pub max_audio_bit_depth: Option<i32>,
    /// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
    pub audio_bit_rate: Option<i32>,
    /// Optional. Specify a specific number of audio channels to encode to, e.g. 2.
    pub audio_channels: Option<i32>,
    /// Optional. Specify a maximum number of audio channels to encode to, e.g. 2.
    pub max_audio_channels: Option<i32>,
    /// Optional. Specify a specific an encoder profile (varies by encoder), e.g. main, baseline, high.
    pub profile: Option<String>,
    /// Optional. Specify a level for the encoder profile (varies by encoder), e.g. 3, 3.1.
    pub level: Option<String>,
    /// Optional. A specific video framerate to encode to, e.g. 23.976. Generally this should be omitted unless the device has specific requirements.
    pub framerate: Option<f32>,
    /// Optional. A specific maximum video framerate to encode to, e.g. 23.976. Generally this should be omitted unless the device has specific requirements.
    pub max_framerate: Option<f32>,
    /// Whether or not to copy timestamps when transcoding with an offset. Defaults to false.
    pub copy_timestamps: Option<bool>,
    /// Optional. Specify a starting offset, in ticks. 1 tick = 10000 ms.
    pub start_time_ticks: Option<i64>,
    /// Optional. The fixed horizontal resolution of the encoded video.
    pub width: Option<i32>,
    /// Optional. The fixed vertical resolution of the encoded video.
    pub height: Option<i32>,
    /// Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults.
    pub video_bit_rate: Option<i32>,
    /// Optional. The index of the subtitle stream to use. If omitted no subtitles will be used.
    pub subtitle_stream_index: Option<i32>,
    /// Optional. Specify the subtitle delivery method.
    pub subtitle_method: Option<String>,
    /// Optional.
    pub max_ref_frames: Option<i32>,
    /// Optional. The maximum video bit depth.
    pub max_video_bit_depth: Option<i32>,
    /// Optional. Whether to require avc.
    pub require_avc: Option<bool>,
    /// Optional. Whether to deinterlace the video.
    pub de_interlace: Option<bool>,
    /// Optional. Whether to require a non anamorphic stream.
    pub require_non_anamorphic: Option<bool>,
    /// Optional. The maximum number of audio channels to transcode.
    pub transcoding_max_audio_channels: Option<i32>,
    /// Optional. The limit of how many cpu cores to use.
    pub cpu_core_limit: Option<i32>,
    /// The live stream id.
    pub live_stream_id: Option<String>,
    /// Optional. Whether to enable the MpegtsM2Ts mode.
    pub enable_mpegts_m2_ts_mode: Option<bool>,
    /// Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url's extension.
    pub video_codec: Option<String>,
    /// Optional. Specify a subtitle codec to encode to.
    pub subtitle_codec: Option<String>,
    /// Optional. The transcoding reason.
    pub transcode_reasons: Option<String>,
    /// Optional. The index of the audio stream to use. If omitted the first audio stream will be used.
    pub audio_stream_index: Option<i32>,
    /// Optional. The index of the video stream to use. If omitted the first video stream will be used.
    pub video_stream_index: Option<i32>,
    /// Optional. The MediaBrowser.Model.Dlna.EncodingContext.
    pub context: Option<String>,
    /// Optional. The streaming options.
    pub stream_options: Option<std::collections::HashMap<String, String>>,
    /// Optional. Whether to enable Audio Encoding.
    pub enable_audio_vbr_encoding: Option<bool>
}

/// struct for passing parameters to the method [`AudioApi::get_universal_audio_stream`]
#[derive(Clone, Debug)]
pub struct GetUniversalAudioStreamParams {
    /// The item id.
    pub item_id: String,
    /// Optional. The audio container.
    pub container: Option<Vec<String>>,
    /// The media version id, if playing an alternate version.
    pub media_source_id: Option<String>,
    /// The device id of the client requesting. Used to stop encoding processes when needed.
    pub device_id: Option<String>,
    /// Optional. The user id.
    pub user_id: Option<String>,
    /// Optional. The audio codec to transcode to.
    pub audio_codec: Option<String>,
    /// Optional. The maximum number of audio channels.
    pub max_audio_channels: Option<i32>,
    /// Optional. The number of how many audio channels to transcode to.
    pub transcoding_audio_channels: Option<i32>,
    /// Optional. The maximum streaming bitrate.
    pub max_streaming_bitrate: Option<i32>,
    /// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
    pub audio_bit_rate: Option<i32>,
    /// Optional. Specify a starting offset, in ticks. 1 tick = 10000 ms.
    pub start_time_ticks: Option<i64>,
    /// Optional. The container to transcode to.
    pub transcoding_container: Option<String>,
    /// Optional. The transcoding protocol.
    pub transcoding_protocol: Option<String>,
    /// Optional. The maximum audio sample rate.
    pub max_audio_sample_rate: Option<i32>,
    /// Optional. The maximum audio bit depth.
    pub max_audio_bit_depth: Option<i32>,
    /// Optional. Whether to enable remote media.
    pub enable_remote_media: Option<bool>,
    /// Optional. Whether to enable Audio Encoding.
    pub enable_audio_vbr_encoding: Option<bool>,
    /// Whether to enable redirection. Defaults to true.
    pub enable_redirection: Option<bool>
}

/// struct for passing parameters to the method [`AudioApi::head_audio_stream`]
#[derive(Clone, Debug)]
pub struct HeadAudioStreamParams {
    /// The item id.
    pub item_id: String,
    /// The audio container.
    pub container: Option<String>,
    /// Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false.
    pub r#static: Option<bool>,
    /// The streaming parameters.
    pub params: Option<String>,
    /// The tag.
    pub tag: Option<String>,
    /// Optional. The dlna device profile id to utilize.
    pub device_profile_id: Option<String>,
    /// The play session id.
    pub play_session_id: Option<String>,
    /// The segment container.
    pub segment_container: Option<String>,
    /// The segment length.
    pub segment_length: Option<i32>,
    /// The minimum number of segments.
    pub min_segments: Option<i32>,
    /// The media version id, if playing an alternate version.
    pub media_source_id: Option<String>,
    /// The device id of the client requesting. Used to stop encoding processes when needed.
    pub device_id: Option<String>,
    /// Optional. Specify an audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url's extension.
    pub audio_codec: Option<String>,
    /// Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true.
    pub enable_auto_stream_copy: Option<bool>,
    /// Whether or not to allow copying of the video stream url.
    pub allow_video_stream_copy: Option<bool>,
    /// Whether or not to allow copying of the audio stream url.
    pub allow_audio_stream_copy: Option<bool>,
    /// Optional. Specify a specific audio sample rate, e.g. 44100.
    pub audio_sample_rate: Option<i32>,
    /// Optional. The maximum audio bit depth.
    pub max_audio_bit_depth: Option<i32>,
    /// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
    pub audio_bit_rate: Option<i32>,
    /// Optional. Specify a specific number of audio channels to encode to, e.g. 2.
    pub audio_channels: Option<i32>,
    /// Optional. Specify a maximum number of audio channels to encode to, e.g. 2.
    pub max_audio_channels: Option<i32>,
    /// Optional. Specify a specific an encoder profile (varies by encoder), e.g. main, baseline, high.
    pub profile: Option<String>,
    /// Optional. Specify a level for the encoder profile (varies by encoder), e.g. 3, 3.1.
    pub level: Option<String>,
    /// Optional. A specific video framerate to encode to, e.g. 23.976. Generally this should be omitted unless the device has specific requirements.
    pub framerate: Option<f32>,
    /// Optional. A specific maximum video framerate to encode to, e.g. 23.976. Generally this should be omitted unless the device has specific requirements.
    pub max_framerate: Option<f32>,
    /// Whether or not to copy timestamps when transcoding with an offset. Defaults to false.
    pub copy_timestamps: Option<bool>,
    /// Optional. Specify a starting offset, in ticks. 1 tick = 10000 ms.
    pub start_time_ticks: Option<i64>,
    /// Optional. The fixed horizontal resolution of the encoded video.
    pub width: Option<i32>,
    /// Optional. The fixed vertical resolution of the encoded video.
    pub height: Option<i32>,
    /// Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults.
    pub video_bit_rate: Option<i32>,
    /// Optional. The index of the subtitle stream to use. If omitted no subtitles will be used.
    pub subtitle_stream_index: Option<i32>,
    /// Optional. Specify the subtitle delivery method.
    pub subtitle_method: Option<String>,
    /// Optional.
    pub max_ref_frames: Option<i32>,
    /// Optional. The maximum video bit depth.
    pub max_video_bit_depth: Option<i32>,
    /// Optional. Whether to require avc.
    pub require_avc: Option<bool>,
    /// Optional. Whether to deinterlace the video.
    pub de_interlace: Option<bool>,
    /// Optional. Whether to require a non anamorphic stream.
    pub require_non_anamorphic: Option<bool>,
    /// Optional. The maximum number of audio channels to transcode.
    pub transcoding_max_audio_channels: Option<i32>,
    /// Optional. The limit of how many cpu cores to use.
    pub cpu_core_limit: Option<i32>,
    /// The live stream id.
    pub live_stream_id: Option<String>,
    /// Optional. Whether to enable the MpegtsM2Ts mode.
    pub enable_mpegts_m2_ts_mode: Option<bool>,
    /// Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url's extension.
    pub video_codec: Option<String>,
    /// Optional. Specify a subtitle codec to encode to.
    pub subtitle_codec: Option<String>,
    /// Optional. The transcoding reason.
    pub transcode_reasons: Option<String>,
    /// Optional. The index of the audio stream to use. If omitted the first audio stream will be used.
    pub audio_stream_index: Option<i32>,
    /// Optional. The index of the video stream to use. If omitted the first video stream will be used.
    pub video_stream_index: Option<i32>,
    /// Optional. The MediaBrowser.Model.Dlna.EncodingContext.
    pub context: Option<String>,
    /// Optional. The streaming options.
    pub stream_options: Option<std::collections::HashMap<String, String>>,
    /// Optional. Whether to enable Audio Encoding.
    pub enable_audio_vbr_encoding: Option<bool>
}

/// struct for passing parameters to the method [`AudioApi::head_audio_stream_by_container`]
#[derive(Clone, Debug)]
pub struct HeadAudioStreamByContainerParams {
    /// The item id.
    pub item_id: String,
    /// The audio container.
    pub container: String,
    /// Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false.
    pub r#static: Option<bool>,
    /// The streaming parameters.
    pub params: Option<String>,
    /// The tag.
    pub tag: Option<String>,
    /// Optional. The dlna device profile id to utilize.
    pub device_profile_id: Option<String>,
    /// The play session id.
    pub play_session_id: Option<String>,
    /// The segment container.
    pub segment_container: Option<String>,
    /// The segment length.
    pub segment_length: Option<i32>,
    /// The minimum number of segments.
    pub min_segments: Option<i32>,
    /// The media version id, if playing an alternate version.
    pub media_source_id: Option<String>,
    /// The device id of the client requesting. Used to stop encoding processes when needed.
    pub device_id: Option<String>,
    /// Optional. Specify an audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url's extension.
    pub audio_codec: Option<String>,
    /// Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true.
    pub enable_auto_stream_copy: Option<bool>,
    /// Whether or not to allow copying of the video stream url.
    pub allow_video_stream_copy: Option<bool>,
    /// Whether or not to allow copying of the audio stream url.
    pub allow_audio_stream_copy: Option<bool>,
    /// Optional. Specify a specific audio sample rate, e.g. 44100.
    pub audio_sample_rate: Option<i32>,
    /// Optional. The maximum audio bit depth.
    pub max_audio_bit_depth: Option<i32>,
    /// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
    pub audio_bit_rate: Option<i32>,
    /// Optional. Specify a specific number of audio channels to encode to, e.g. 2.
    pub audio_channels: Option<i32>,
    /// Optional. Specify a maximum number of audio channels to encode to, e.g. 2.
    pub max_audio_channels: Option<i32>,
    /// Optional. Specify a specific an encoder profile (varies by encoder), e.g. main, baseline, high.
    pub profile: Option<String>,
    /// Optional. Specify a level for the encoder profile (varies by encoder), e.g. 3, 3.1.
    pub level: Option<String>,
    /// Optional. A specific video framerate to encode to, e.g. 23.976. Generally this should be omitted unless the device has specific requirements.
    pub framerate: Option<f32>,
    /// Optional. A specific maximum video framerate to encode to, e.g. 23.976. Generally this should be omitted unless the device has specific requirements.
    pub max_framerate: Option<f32>,
    /// Whether or not to copy timestamps when transcoding with an offset. Defaults to false.
    pub copy_timestamps: Option<bool>,
    /// Optional. Specify a starting offset, in ticks. 1 tick = 10000 ms.
    pub start_time_ticks: Option<i64>,
    /// Optional. The fixed horizontal resolution of the encoded video.
    pub width: Option<i32>,
    /// Optional. The fixed vertical resolution of the encoded video.
    pub height: Option<i32>,
    /// Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults.
    pub video_bit_rate: Option<i32>,
    /// Optional. The index of the subtitle stream to use. If omitted no subtitles will be used.
    pub subtitle_stream_index: Option<i32>,
    /// Optional. Specify the subtitle delivery method.
    pub subtitle_method: Option<String>,
    /// Optional.
    pub max_ref_frames: Option<i32>,
    /// Optional. The maximum video bit depth.
    pub max_video_bit_depth: Option<i32>,
    /// Optional. Whether to require avc.
    pub require_avc: Option<bool>,
    /// Optional. Whether to deinterlace the video.
    pub de_interlace: Option<bool>,
    /// Optional. Whether to require a non anamorphic stream.
    pub require_non_anamorphic: Option<bool>,
    /// Optional. The maximum number of audio channels to transcode.
    pub transcoding_max_audio_channels: Option<i32>,
    /// Optional. The limit of how many cpu cores to use.
    pub cpu_core_limit: Option<i32>,
    /// The live stream id.
    pub live_stream_id: Option<String>,
    /// Optional. Whether to enable the MpegtsM2Ts mode.
    pub enable_mpegts_m2_ts_mode: Option<bool>,
    /// Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url's extension.
    pub video_codec: Option<String>,
    /// Optional. Specify a subtitle codec to encode to.
    pub subtitle_codec: Option<String>,
    /// Optional. The transcoding reason.
    pub transcode_reasons: Option<String>,
    /// Optional. The index of the audio stream to use. If omitted the first audio stream will be used.
    pub audio_stream_index: Option<i32>,
    /// Optional. The index of the video stream to use. If omitted the first video stream will be used.
    pub video_stream_index: Option<i32>,
    /// Optional. The MediaBrowser.Model.Dlna.EncodingContext.
    pub context: Option<String>,
    /// Optional. The streaming options.
    pub stream_options: Option<std::collections::HashMap<String, String>>,
    /// Optional. Whether to enable Audio Encoding.
    pub enable_audio_vbr_encoding: Option<bool>
}

/// struct for passing parameters to the method [`AudioApi::head_universal_audio_stream`]
#[derive(Clone, Debug)]
pub struct HeadUniversalAudioStreamParams {
    /// The item id.
    pub item_id: String,
    /// Optional. The audio container.
    pub container: Option<Vec<String>>,
    /// The media version id, if playing an alternate version.
    pub media_source_id: Option<String>,
    /// The device id of the client requesting. Used to stop encoding processes when needed.
    pub device_id: Option<String>,
    /// Optional. The user id.
    pub user_id: Option<String>,
    /// Optional. The audio codec to transcode to.
    pub audio_codec: Option<String>,
    /// Optional. The maximum number of audio channels.
    pub max_audio_channels: Option<i32>,
    /// Optional. The number of how many audio channels to transcode to.
    pub transcoding_audio_channels: Option<i32>,
    /// Optional. The maximum streaming bitrate.
    pub max_streaming_bitrate: Option<i32>,
    /// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
    pub audio_bit_rate: Option<i32>,
    /// Optional. Specify a starting offset, in ticks. 1 tick = 10000 ms.
    pub start_time_ticks: Option<i64>,
    /// Optional. The container to transcode to.
    pub transcoding_container: Option<String>,
    /// Optional. The transcoding protocol.
    pub transcoding_protocol: Option<String>,
    /// Optional. The maximum audio sample rate.
    pub max_audio_sample_rate: Option<i32>,
    /// Optional. The maximum audio bit depth.
    pub max_audio_bit_depth: Option<i32>,
    /// Optional. Whether to enable remote media.
    pub enable_remote_media: Option<bool>,
    /// Optional. Whether to enable Audio Encoding.
    pub enable_audio_vbr_encoding: Option<bool>,
    /// Whether to enable redirection. Defaults to true.
    pub enable_redirection: Option<bool>
}


#[async_trait]
impl AudioApi for AudioApiClient {
    async fn get_audio_stream(&self,  params: GetAudioStreamParams ) -> Result<std::path::PathBuf, Error<GetAudioStreamError>> {
        
        let GetAudioStreamParams {
            item_id,
            container,
            r#static,
            params,
            tag,
            device_profile_id,
            play_session_id,
            segment_container,
            segment_length,
            min_segments,
            media_source_id,
            device_id,
            audio_codec,
            enable_auto_stream_copy,
            allow_video_stream_copy,
            allow_audio_stream_copy,
            audio_sample_rate,
            max_audio_bit_depth,
            audio_bit_rate,
            audio_channels,
            max_audio_channels,
            profile,
            level,
            framerate,
            max_framerate,
            copy_timestamps,
            start_time_ticks,
            width,
            height,
            video_bit_rate,
            subtitle_stream_index,
            subtitle_method,
            max_ref_frames,
            max_video_bit_depth,
            require_avc,
            de_interlace,
            require_non_anamorphic,
            transcoding_max_audio_channels,
            cpu_core_limit,
            live_stream_id,
            enable_mpegts_m2_ts_mode,
            video_codec,
            subtitle_codec,
            transcode_reasons,
            audio_stream_index,
            video_stream_index,
            context,
            stream_options,
            enable_audio_vbr_encoding,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Audio/{itemId}/stream", local_var_configuration.base_path, itemId=crate::apis::urlencode(item_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = container {
            local_var_req_builder = local_var_req_builder.query(&[("container", &param_value.to_string())]);
        }
        if let Some(ref param_value) = r#static {
            local_var_req_builder = local_var_req_builder.query(&[("static", &param_value.to_string())]);
        }
        if let Some(ref param_value) = params {
            local_var_req_builder = local_var_req_builder.query(&[("params", &param_value.to_string())]);
        }
        if let Some(ref param_value) = tag {
            local_var_req_builder = local_var_req_builder.query(&[("tag", &param_value.to_string())]);
        }
        if let Some(ref param_value) = device_profile_id {
            local_var_req_builder = local_var_req_builder.query(&[("deviceProfileId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = play_session_id {
            local_var_req_builder = local_var_req_builder.query(&[("playSessionId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = segment_container {
            local_var_req_builder = local_var_req_builder.query(&[("segmentContainer", &param_value.to_string())]);
        }
        if let Some(ref param_value) = segment_length {
            local_var_req_builder = local_var_req_builder.query(&[("segmentLength", &param_value.to_string())]);
        }
        if let Some(ref param_value) = min_segments {
            local_var_req_builder = local_var_req_builder.query(&[("minSegments", &param_value.to_string())]);
        }
        if let Some(ref param_value) = media_source_id {
            local_var_req_builder = local_var_req_builder.query(&[("mediaSourceId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = device_id {
            local_var_req_builder = local_var_req_builder.query(&[("deviceId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_codec {
            local_var_req_builder = local_var_req_builder.query(&[("audioCodec", &param_value.to_string())]);
        }
        if let Some(ref param_value) = enable_auto_stream_copy {
            local_var_req_builder = local_var_req_builder.query(&[("enableAutoStreamCopy", &param_value.to_string())]);
        }
        if let Some(ref param_value) = allow_video_stream_copy {
            local_var_req_builder = local_var_req_builder.query(&[("allowVideoStreamCopy", &param_value.to_string())]);
        }
        if let Some(ref param_value) = allow_audio_stream_copy {
            local_var_req_builder = local_var_req_builder.query(&[("allowAudioStreamCopy", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_sample_rate {
            local_var_req_builder = local_var_req_builder.query(&[("audioSampleRate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_audio_bit_depth {
            local_var_req_builder = local_var_req_builder.query(&[("maxAudioBitDepth", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_bit_rate {
            local_var_req_builder = local_var_req_builder.query(&[("audioBitRate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_channels {
            local_var_req_builder = local_var_req_builder.query(&[("audioChannels", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_audio_channels {
            local_var_req_builder = local_var_req_builder.query(&[("maxAudioChannels", &param_value.to_string())]);
        }
        if let Some(ref param_value) = profile {
            local_var_req_builder = local_var_req_builder.query(&[("profile", &param_value.to_string())]);
        }
        if let Some(ref param_value) = level {
            local_var_req_builder = local_var_req_builder.query(&[("level", &param_value.to_string())]);
        }
        if let Some(ref param_value) = framerate {
            local_var_req_builder = local_var_req_builder.query(&[("framerate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_framerate {
            local_var_req_builder = local_var_req_builder.query(&[("maxFramerate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = copy_timestamps {
            local_var_req_builder = local_var_req_builder.query(&[("copyTimestamps", &param_value.to_string())]);
        }
        if let Some(ref param_value) = start_time_ticks {
            local_var_req_builder = local_var_req_builder.query(&[("startTimeTicks", &param_value.to_string())]);
        }
        if let Some(ref param_value) = width {
            local_var_req_builder = local_var_req_builder.query(&[("width", &param_value.to_string())]);
        }
        if let Some(ref param_value) = height {
            local_var_req_builder = local_var_req_builder.query(&[("height", &param_value.to_string())]);
        }
        if let Some(ref param_value) = video_bit_rate {
            local_var_req_builder = local_var_req_builder.query(&[("videoBitRate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = subtitle_stream_index {
            local_var_req_builder = local_var_req_builder.query(&[("subtitleStreamIndex", &param_value.to_string())]);
        }
        if let Some(ref param_value) = subtitle_method {
            local_var_req_builder = local_var_req_builder.query(&[("subtitleMethod", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_ref_frames {
            local_var_req_builder = local_var_req_builder.query(&[("maxRefFrames", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_video_bit_depth {
            local_var_req_builder = local_var_req_builder.query(&[("maxVideoBitDepth", &param_value.to_string())]);
        }
        if let Some(ref param_value) = require_avc {
            local_var_req_builder = local_var_req_builder.query(&[("requireAvc", &param_value.to_string())]);
        }
        if let Some(ref param_value) = de_interlace {
            local_var_req_builder = local_var_req_builder.query(&[("deInterlace", &param_value.to_string())]);
        }
        if let Some(ref param_value) = require_non_anamorphic {
            local_var_req_builder = local_var_req_builder.query(&[("requireNonAnamorphic", &param_value.to_string())]);
        }
        if let Some(ref param_value) = transcoding_max_audio_channels {
            local_var_req_builder = local_var_req_builder.query(&[("transcodingMaxAudioChannels", &param_value.to_string())]);
        }
        if let Some(ref param_value) = cpu_core_limit {
            local_var_req_builder = local_var_req_builder.query(&[("cpuCoreLimit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = live_stream_id {
            local_var_req_builder = local_var_req_builder.query(&[("liveStreamId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = enable_mpegts_m2_ts_mode {
            local_var_req_builder = local_var_req_builder.query(&[("enableMpegtsM2TsMode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = video_codec {
            local_var_req_builder = local_var_req_builder.query(&[("videoCodec", &param_value.to_string())]);
        }
        if let Some(ref param_value) = subtitle_codec {
            local_var_req_builder = local_var_req_builder.query(&[("subtitleCodec", &param_value.to_string())]);
        }
        if let Some(ref param_value) = transcode_reasons {
            local_var_req_builder = local_var_req_builder.query(&[("transcodeReasons", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_stream_index {
            local_var_req_builder = local_var_req_builder.query(&[("audioStreamIndex", &param_value.to_string())]);
        }
        if let Some(ref param_value) = video_stream_index {
            local_var_req_builder = local_var_req_builder.query(&[("videoStreamIndex", &param_value.to_string())]);
        }
        if let Some(ref param_value) = context {
            local_var_req_builder = local_var_req_builder.query(&[("context", &param_value.to_string())]);
        }
        if let Some(ref param_value) = stream_options {
            let params = crate::apis::parse_deep_object("streamOptions", &serde_json::to_value(param_value)?);
            local_var_req_builder = local_var_req_builder.query(&params);
        }
        if let Some(ref param_value) = enable_audio_vbr_encoding {
            local_var_req_builder = local_var_req_builder.query(&[("enableAudioVbrEncoding", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `std::path::PathBuf`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `std::path::PathBuf`")))),
            }
        } else {
            let local_var_entity: Option<GetAudioStreamError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_audio_stream_by_container(&self,  params: GetAudioStreamByContainerParams ) -> Result<std::path::PathBuf, Error<GetAudioStreamByContainerError>> {
        
        let GetAudioStreamByContainerParams {
            item_id,
            container,
            r#static,
            params,
            tag,
            device_profile_id,
            play_session_id,
            segment_container,
            segment_length,
            min_segments,
            media_source_id,
            device_id,
            audio_codec,
            enable_auto_stream_copy,
            allow_video_stream_copy,
            allow_audio_stream_copy,
            audio_sample_rate,
            max_audio_bit_depth,
            audio_bit_rate,
            audio_channels,
            max_audio_channels,
            profile,
            level,
            framerate,
            max_framerate,
            copy_timestamps,
            start_time_ticks,
            width,
            height,
            video_bit_rate,
            subtitle_stream_index,
            subtitle_method,
            max_ref_frames,
            max_video_bit_depth,
            require_avc,
            de_interlace,
            require_non_anamorphic,
            transcoding_max_audio_channels,
            cpu_core_limit,
            live_stream_id,
            enable_mpegts_m2_ts_mode,
            video_codec,
            subtitle_codec,
            transcode_reasons,
            audio_stream_index,
            video_stream_index,
            context,
            stream_options,
            enable_audio_vbr_encoding,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Audio/{itemId}/stream.{container}", local_var_configuration.base_path, itemId=crate::apis::urlencode(item_id), container=crate::apis::urlencode(container));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = r#static {
            local_var_req_builder = local_var_req_builder.query(&[("static", &param_value.to_string())]);
        }
        if let Some(ref param_value) = params {
            local_var_req_builder = local_var_req_builder.query(&[("params", &param_value.to_string())]);
        }
        if let Some(ref param_value) = tag {
            local_var_req_builder = local_var_req_builder.query(&[("tag", &param_value.to_string())]);
        }
        if let Some(ref param_value) = device_profile_id {
            local_var_req_builder = local_var_req_builder.query(&[("deviceProfileId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = play_session_id {
            local_var_req_builder = local_var_req_builder.query(&[("playSessionId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = segment_container {
            local_var_req_builder = local_var_req_builder.query(&[("segmentContainer", &param_value.to_string())]);
        }
        if let Some(ref param_value) = segment_length {
            local_var_req_builder = local_var_req_builder.query(&[("segmentLength", &param_value.to_string())]);
        }
        if let Some(ref param_value) = min_segments {
            local_var_req_builder = local_var_req_builder.query(&[("minSegments", &param_value.to_string())]);
        }
        if let Some(ref param_value) = media_source_id {
            local_var_req_builder = local_var_req_builder.query(&[("mediaSourceId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = device_id {
            local_var_req_builder = local_var_req_builder.query(&[("deviceId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_codec {
            local_var_req_builder = local_var_req_builder.query(&[("audioCodec", &param_value.to_string())]);
        }
        if let Some(ref param_value) = enable_auto_stream_copy {
            local_var_req_builder = local_var_req_builder.query(&[("enableAutoStreamCopy", &param_value.to_string())]);
        }
        if let Some(ref param_value) = allow_video_stream_copy {
            local_var_req_builder = local_var_req_builder.query(&[("allowVideoStreamCopy", &param_value.to_string())]);
        }
        if let Some(ref param_value) = allow_audio_stream_copy {
            local_var_req_builder = local_var_req_builder.query(&[("allowAudioStreamCopy", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_sample_rate {
            local_var_req_builder = local_var_req_builder.query(&[("audioSampleRate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_audio_bit_depth {
            local_var_req_builder = local_var_req_builder.query(&[("maxAudioBitDepth", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_bit_rate {
            local_var_req_builder = local_var_req_builder.query(&[("audioBitRate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_channels {
            local_var_req_builder = local_var_req_builder.query(&[("audioChannels", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_audio_channels {
            local_var_req_builder = local_var_req_builder.query(&[("maxAudioChannels", &param_value.to_string())]);
        }
        if let Some(ref param_value) = profile {
            local_var_req_builder = local_var_req_builder.query(&[("profile", &param_value.to_string())]);
        }
        if let Some(ref param_value) = level {
            local_var_req_builder = local_var_req_builder.query(&[("level", &param_value.to_string())]);
        }
        if let Some(ref param_value) = framerate {
            local_var_req_builder = local_var_req_builder.query(&[("framerate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_framerate {
            local_var_req_builder = local_var_req_builder.query(&[("maxFramerate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = copy_timestamps {
            local_var_req_builder = local_var_req_builder.query(&[("copyTimestamps", &param_value.to_string())]);
        }
        if let Some(ref param_value) = start_time_ticks {
            local_var_req_builder = local_var_req_builder.query(&[("startTimeTicks", &param_value.to_string())]);
        }
        if let Some(ref param_value) = width {
            local_var_req_builder = local_var_req_builder.query(&[("width", &param_value.to_string())]);
        }
        if let Some(ref param_value) = height {
            local_var_req_builder = local_var_req_builder.query(&[("height", &param_value.to_string())]);
        }
        if let Some(ref param_value) = video_bit_rate {
            local_var_req_builder = local_var_req_builder.query(&[("videoBitRate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = subtitle_stream_index {
            local_var_req_builder = local_var_req_builder.query(&[("subtitleStreamIndex", &param_value.to_string())]);
        }
        if let Some(ref param_value) = subtitle_method {
            local_var_req_builder = local_var_req_builder.query(&[("subtitleMethod", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_ref_frames {
            local_var_req_builder = local_var_req_builder.query(&[("maxRefFrames", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_video_bit_depth {
            local_var_req_builder = local_var_req_builder.query(&[("maxVideoBitDepth", &param_value.to_string())]);
        }
        if let Some(ref param_value) = require_avc {
            local_var_req_builder = local_var_req_builder.query(&[("requireAvc", &param_value.to_string())]);
        }
        if let Some(ref param_value) = de_interlace {
            local_var_req_builder = local_var_req_builder.query(&[("deInterlace", &param_value.to_string())]);
        }
        if let Some(ref param_value) = require_non_anamorphic {
            local_var_req_builder = local_var_req_builder.query(&[("requireNonAnamorphic", &param_value.to_string())]);
        }
        if let Some(ref param_value) = transcoding_max_audio_channels {
            local_var_req_builder = local_var_req_builder.query(&[("transcodingMaxAudioChannels", &param_value.to_string())]);
        }
        if let Some(ref param_value) = cpu_core_limit {
            local_var_req_builder = local_var_req_builder.query(&[("cpuCoreLimit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = live_stream_id {
            local_var_req_builder = local_var_req_builder.query(&[("liveStreamId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = enable_mpegts_m2_ts_mode {
            local_var_req_builder = local_var_req_builder.query(&[("enableMpegtsM2TsMode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = video_codec {
            local_var_req_builder = local_var_req_builder.query(&[("videoCodec", &param_value.to_string())]);
        }
        if let Some(ref param_value) = subtitle_codec {
            local_var_req_builder = local_var_req_builder.query(&[("subtitleCodec", &param_value.to_string())]);
        }
        if let Some(ref param_value) = transcode_reasons {
            local_var_req_builder = local_var_req_builder.query(&[("transcodeReasons", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_stream_index {
            local_var_req_builder = local_var_req_builder.query(&[("audioStreamIndex", &param_value.to_string())]);
        }
        if let Some(ref param_value) = video_stream_index {
            local_var_req_builder = local_var_req_builder.query(&[("videoStreamIndex", &param_value.to_string())]);
        }
        if let Some(ref param_value) = context {
            local_var_req_builder = local_var_req_builder.query(&[("context", &param_value.to_string())]);
        }
        if let Some(ref param_value) = stream_options {
            let params = crate::apis::parse_deep_object("streamOptions", &serde_json::to_value(param_value)?);
            local_var_req_builder = local_var_req_builder.query(&params);
        }
        if let Some(ref param_value) = enable_audio_vbr_encoding {
            local_var_req_builder = local_var_req_builder.query(&[("enableAudioVbrEncoding", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `std::path::PathBuf`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `std::path::PathBuf`")))),
            }
        } else {
            let local_var_entity: Option<GetAudioStreamByContainerError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_universal_audio_stream(&self,  params: GetUniversalAudioStreamParams ) -> Result<std::path::PathBuf, Error<GetUniversalAudioStreamError>> {
        
        let GetUniversalAudioStreamParams {
            item_id,
            container,
            media_source_id,
            device_id,
            user_id,
            audio_codec,
            max_audio_channels,
            transcoding_audio_channels,
            max_streaming_bitrate,
            audio_bit_rate,
            start_time_ticks,
            transcoding_container,
            transcoding_protocol,
            max_audio_sample_rate,
            max_audio_bit_depth,
            enable_remote_media,
            enable_audio_vbr_encoding,
            enable_redirection,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Audio/{itemId}/universal", local_var_configuration.base_path, itemId=crate::apis::urlencode(item_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = container {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(&param_value.into_iter().map(|p| ("container".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
                _ => local_var_req_builder.query(&[("container", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
            };
        }
        if let Some(ref param_value) = media_source_id {
            local_var_req_builder = local_var_req_builder.query(&[("mediaSourceId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = device_id {
            local_var_req_builder = local_var_req_builder.query(&[("deviceId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = user_id {
            local_var_req_builder = local_var_req_builder.query(&[("userId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_codec {
            local_var_req_builder = local_var_req_builder.query(&[("audioCodec", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_audio_channels {
            local_var_req_builder = local_var_req_builder.query(&[("maxAudioChannels", &param_value.to_string())]);
        }
        if let Some(ref param_value) = transcoding_audio_channels {
            local_var_req_builder = local_var_req_builder.query(&[("transcodingAudioChannels", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_streaming_bitrate {
            local_var_req_builder = local_var_req_builder.query(&[("maxStreamingBitrate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_bit_rate {
            local_var_req_builder = local_var_req_builder.query(&[("audioBitRate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = start_time_ticks {
            local_var_req_builder = local_var_req_builder.query(&[("startTimeTicks", &param_value.to_string())]);
        }
        if let Some(ref param_value) = transcoding_container {
            local_var_req_builder = local_var_req_builder.query(&[("transcodingContainer", &param_value.to_string())]);
        }
        if let Some(ref param_value) = transcoding_protocol {
            local_var_req_builder = local_var_req_builder.query(&[("transcodingProtocol", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_audio_sample_rate {
            local_var_req_builder = local_var_req_builder.query(&[("maxAudioSampleRate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_audio_bit_depth {
            local_var_req_builder = local_var_req_builder.query(&[("maxAudioBitDepth", &param_value.to_string())]);
        }
        if let Some(ref param_value) = enable_remote_media {
            local_var_req_builder = local_var_req_builder.query(&[("enableRemoteMedia", &param_value.to_string())]);
        }
        if let Some(ref param_value) = enable_audio_vbr_encoding {
            local_var_req_builder = local_var_req_builder.query(&[("enableAudioVbrEncoding", &param_value.to_string())]);
        }
        if let Some(ref param_value) = enable_redirection {
            local_var_req_builder = local_var_req_builder.query(&[("enableRedirection", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `std::path::PathBuf`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `std::path::PathBuf`")))),
            }
        } else {
            let local_var_entity: Option<GetUniversalAudioStreamError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn head_audio_stream(&self,  params: HeadAudioStreamParams ) -> Result<std::path::PathBuf, Error<HeadAudioStreamError>> {
        
        let HeadAudioStreamParams {
            item_id,
            container,
            r#static,
            params,
            tag,
            device_profile_id,
            play_session_id,
            segment_container,
            segment_length,
            min_segments,
            media_source_id,
            device_id,
            audio_codec,
            enable_auto_stream_copy,
            allow_video_stream_copy,
            allow_audio_stream_copy,
            audio_sample_rate,
            max_audio_bit_depth,
            audio_bit_rate,
            audio_channels,
            max_audio_channels,
            profile,
            level,
            framerate,
            max_framerate,
            copy_timestamps,
            start_time_ticks,
            width,
            height,
            video_bit_rate,
            subtitle_stream_index,
            subtitle_method,
            max_ref_frames,
            max_video_bit_depth,
            require_avc,
            de_interlace,
            require_non_anamorphic,
            transcoding_max_audio_channels,
            cpu_core_limit,
            live_stream_id,
            enable_mpegts_m2_ts_mode,
            video_codec,
            subtitle_codec,
            transcode_reasons,
            audio_stream_index,
            video_stream_index,
            context,
            stream_options,
            enable_audio_vbr_encoding,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Audio/{itemId}/stream", local_var_configuration.base_path, itemId=crate::apis::urlencode(item_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::HEAD, local_var_uri_str.as_str());

        if let Some(ref param_value) = container {
            local_var_req_builder = local_var_req_builder.query(&[("container", &param_value.to_string())]);
        }
        if let Some(ref param_value) = r#static {
            local_var_req_builder = local_var_req_builder.query(&[("static", &param_value.to_string())]);
        }
        if let Some(ref param_value) = params {
            local_var_req_builder = local_var_req_builder.query(&[("params", &param_value.to_string())]);
        }
        if let Some(ref param_value) = tag {
            local_var_req_builder = local_var_req_builder.query(&[("tag", &param_value.to_string())]);
        }
        if let Some(ref param_value) = device_profile_id {
            local_var_req_builder = local_var_req_builder.query(&[("deviceProfileId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = play_session_id {
            local_var_req_builder = local_var_req_builder.query(&[("playSessionId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = segment_container {
            local_var_req_builder = local_var_req_builder.query(&[("segmentContainer", &param_value.to_string())]);
        }
        if let Some(ref param_value) = segment_length {
            local_var_req_builder = local_var_req_builder.query(&[("segmentLength", &param_value.to_string())]);
        }
        if let Some(ref param_value) = min_segments {
            local_var_req_builder = local_var_req_builder.query(&[("minSegments", &param_value.to_string())]);
        }
        if let Some(ref param_value) = media_source_id {
            local_var_req_builder = local_var_req_builder.query(&[("mediaSourceId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = device_id {
            local_var_req_builder = local_var_req_builder.query(&[("deviceId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_codec {
            local_var_req_builder = local_var_req_builder.query(&[("audioCodec", &param_value.to_string())]);
        }
        if let Some(ref param_value) = enable_auto_stream_copy {
            local_var_req_builder = local_var_req_builder.query(&[("enableAutoStreamCopy", &param_value.to_string())]);
        }
        if let Some(ref param_value) = allow_video_stream_copy {
            local_var_req_builder = local_var_req_builder.query(&[("allowVideoStreamCopy", &param_value.to_string())]);
        }
        if let Some(ref param_value) = allow_audio_stream_copy {
            local_var_req_builder = local_var_req_builder.query(&[("allowAudioStreamCopy", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_sample_rate {
            local_var_req_builder = local_var_req_builder.query(&[("audioSampleRate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_audio_bit_depth {
            local_var_req_builder = local_var_req_builder.query(&[("maxAudioBitDepth", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_bit_rate {
            local_var_req_builder = local_var_req_builder.query(&[("audioBitRate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_channels {
            local_var_req_builder = local_var_req_builder.query(&[("audioChannels", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_audio_channels {
            local_var_req_builder = local_var_req_builder.query(&[("maxAudioChannels", &param_value.to_string())]);
        }
        if let Some(ref param_value) = profile {
            local_var_req_builder = local_var_req_builder.query(&[("profile", &param_value.to_string())]);
        }
        if let Some(ref param_value) = level {
            local_var_req_builder = local_var_req_builder.query(&[("level", &param_value.to_string())]);
        }
        if let Some(ref param_value) = framerate {
            local_var_req_builder = local_var_req_builder.query(&[("framerate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_framerate {
            local_var_req_builder = local_var_req_builder.query(&[("maxFramerate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = copy_timestamps {
            local_var_req_builder = local_var_req_builder.query(&[("copyTimestamps", &param_value.to_string())]);
        }
        if let Some(ref param_value) = start_time_ticks {
            local_var_req_builder = local_var_req_builder.query(&[("startTimeTicks", &param_value.to_string())]);
        }
        if let Some(ref param_value) = width {
            local_var_req_builder = local_var_req_builder.query(&[("width", &param_value.to_string())]);
        }
        if let Some(ref param_value) = height {
            local_var_req_builder = local_var_req_builder.query(&[("height", &param_value.to_string())]);
        }
        if let Some(ref param_value) = video_bit_rate {
            local_var_req_builder = local_var_req_builder.query(&[("videoBitRate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = subtitle_stream_index {
            local_var_req_builder = local_var_req_builder.query(&[("subtitleStreamIndex", &param_value.to_string())]);
        }
        if let Some(ref param_value) = subtitle_method {
            local_var_req_builder = local_var_req_builder.query(&[("subtitleMethod", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_ref_frames {
            local_var_req_builder = local_var_req_builder.query(&[("maxRefFrames", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_video_bit_depth {
            local_var_req_builder = local_var_req_builder.query(&[("maxVideoBitDepth", &param_value.to_string())]);
        }
        if let Some(ref param_value) = require_avc {
            local_var_req_builder = local_var_req_builder.query(&[("requireAvc", &param_value.to_string())]);
        }
        if let Some(ref param_value) = de_interlace {
            local_var_req_builder = local_var_req_builder.query(&[("deInterlace", &param_value.to_string())]);
        }
        if let Some(ref param_value) = require_non_anamorphic {
            local_var_req_builder = local_var_req_builder.query(&[("requireNonAnamorphic", &param_value.to_string())]);
        }
        if let Some(ref param_value) = transcoding_max_audio_channels {
            local_var_req_builder = local_var_req_builder.query(&[("transcodingMaxAudioChannels", &param_value.to_string())]);
        }
        if let Some(ref param_value) = cpu_core_limit {
            local_var_req_builder = local_var_req_builder.query(&[("cpuCoreLimit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = live_stream_id {
            local_var_req_builder = local_var_req_builder.query(&[("liveStreamId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = enable_mpegts_m2_ts_mode {
            local_var_req_builder = local_var_req_builder.query(&[("enableMpegtsM2TsMode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = video_codec {
            local_var_req_builder = local_var_req_builder.query(&[("videoCodec", &param_value.to_string())]);
        }
        if let Some(ref param_value) = subtitle_codec {
            local_var_req_builder = local_var_req_builder.query(&[("subtitleCodec", &param_value.to_string())]);
        }
        if let Some(ref param_value) = transcode_reasons {
            local_var_req_builder = local_var_req_builder.query(&[("transcodeReasons", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_stream_index {
            local_var_req_builder = local_var_req_builder.query(&[("audioStreamIndex", &param_value.to_string())]);
        }
        if let Some(ref param_value) = video_stream_index {
            local_var_req_builder = local_var_req_builder.query(&[("videoStreamIndex", &param_value.to_string())]);
        }
        if let Some(ref param_value) = context {
            local_var_req_builder = local_var_req_builder.query(&[("context", &param_value.to_string())]);
        }
        if let Some(ref param_value) = stream_options {
            let params = crate::apis::parse_deep_object("streamOptions", &serde_json::to_value(param_value)?);
            local_var_req_builder = local_var_req_builder.query(&params);
        }
        if let Some(ref param_value) = enable_audio_vbr_encoding {
            local_var_req_builder = local_var_req_builder.query(&[("enableAudioVbrEncoding", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `std::path::PathBuf`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `std::path::PathBuf`")))),
            }
        } else {
            let local_var_entity: Option<HeadAudioStreamError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn head_audio_stream_by_container(&self,  params: HeadAudioStreamByContainerParams ) -> Result<std::path::PathBuf, Error<HeadAudioStreamByContainerError>> {
        
        let HeadAudioStreamByContainerParams {
            item_id,
            container,
            r#static,
            params,
            tag,
            device_profile_id,
            play_session_id,
            segment_container,
            segment_length,
            min_segments,
            media_source_id,
            device_id,
            audio_codec,
            enable_auto_stream_copy,
            allow_video_stream_copy,
            allow_audio_stream_copy,
            audio_sample_rate,
            max_audio_bit_depth,
            audio_bit_rate,
            audio_channels,
            max_audio_channels,
            profile,
            level,
            framerate,
            max_framerate,
            copy_timestamps,
            start_time_ticks,
            width,
            height,
            video_bit_rate,
            subtitle_stream_index,
            subtitle_method,
            max_ref_frames,
            max_video_bit_depth,
            require_avc,
            de_interlace,
            require_non_anamorphic,
            transcoding_max_audio_channels,
            cpu_core_limit,
            live_stream_id,
            enable_mpegts_m2_ts_mode,
            video_codec,
            subtitle_codec,
            transcode_reasons,
            audio_stream_index,
            video_stream_index,
            context,
            stream_options,
            enable_audio_vbr_encoding,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Audio/{itemId}/stream.{container}", local_var_configuration.base_path, itemId=crate::apis::urlencode(item_id), container=crate::apis::urlencode(container));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::HEAD, local_var_uri_str.as_str());

        if let Some(ref param_value) = r#static {
            local_var_req_builder = local_var_req_builder.query(&[("static", &param_value.to_string())]);
        }
        if let Some(ref param_value) = params {
            local_var_req_builder = local_var_req_builder.query(&[("params", &param_value.to_string())]);
        }
        if let Some(ref param_value) = tag {
            local_var_req_builder = local_var_req_builder.query(&[("tag", &param_value.to_string())]);
        }
        if let Some(ref param_value) = device_profile_id {
            local_var_req_builder = local_var_req_builder.query(&[("deviceProfileId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = play_session_id {
            local_var_req_builder = local_var_req_builder.query(&[("playSessionId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = segment_container {
            local_var_req_builder = local_var_req_builder.query(&[("segmentContainer", &param_value.to_string())]);
        }
        if let Some(ref param_value) = segment_length {
            local_var_req_builder = local_var_req_builder.query(&[("segmentLength", &param_value.to_string())]);
        }
        if let Some(ref param_value) = min_segments {
            local_var_req_builder = local_var_req_builder.query(&[("minSegments", &param_value.to_string())]);
        }
        if let Some(ref param_value) = media_source_id {
            local_var_req_builder = local_var_req_builder.query(&[("mediaSourceId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = device_id {
            local_var_req_builder = local_var_req_builder.query(&[("deviceId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_codec {
            local_var_req_builder = local_var_req_builder.query(&[("audioCodec", &param_value.to_string())]);
        }
        if let Some(ref param_value) = enable_auto_stream_copy {
            local_var_req_builder = local_var_req_builder.query(&[("enableAutoStreamCopy", &param_value.to_string())]);
        }
        if let Some(ref param_value) = allow_video_stream_copy {
            local_var_req_builder = local_var_req_builder.query(&[("allowVideoStreamCopy", &param_value.to_string())]);
        }
        if let Some(ref param_value) = allow_audio_stream_copy {
            local_var_req_builder = local_var_req_builder.query(&[("allowAudioStreamCopy", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_sample_rate {
            local_var_req_builder = local_var_req_builder.query(&[("audioSampleRate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_audio_bit_depth {
            local_var_req_builder = local_var_req_builder.query(&[("maxAudioBitDepth", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_bit_rate {
            local_var_req_builder = local_var_req_builder.query(&[("audioBitRate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_channels {
            local_var_req_builder = local_var_req_builder.query(&[("audioChannels", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_audio_channels {
            local_var_req_builder = local_var_req_builder.query(&[("maxAudioChannels", &param_value.to_string())]);
        }
        if let Some(ref param_value) = profile {
            local_var_req_builder = local_var_req_builder.query(&[("profile", &param_value.to_string())]);
        }
        if let Some(ref param_value) = level {
            local_var_req_builder = local_var_req_builder.query(&[("level", &param_value.to_string())]);
        }
        if let Some(ref param_value) = framerate {
            local_var_req_builder = local_var_req_builder.query(&[("framerate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_framerate {
            local_var_req_builder = local_var_req_builder.query(&[("maxFramerate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = copy_timestamps {
            local_var_req_builder = local_var_req_builder.query(&[("copyTimestamps", &param_value.to_string())]);
        }
        if let Some(ref param_value) = start_time_ticks {
            local_var_req_builder = local_var_req_builder.query(&[("startTimeTicks", &param_value.to_string())]);
        }
        if let Some(ref param_value) = width {
            local_var_req_builder = local_var_req_builder.query(&[("width", &param_value.to_string())]);
        }
        if let Some(ref param_value) = height {
            local_var_req_builder = local_var_req_builder.query(&[("height", &param_value.to_string())]);
        }
        if let Some(ref param_value) = video_bit_rate {
            local_var_req_builder = local_var_req_builder.query(&[("videoBitRate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = subtitle_stream_index {
            local_var_req_builder = local_var_req_builder.query(&[("subtitleStreamIndex", &param_value.to_string())]);
        }
        if let Some(ref param_value) = subtitle_method {
            local_var_req_builder = local_var_req_builder.query(&[("subtitleMethod", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_ref_frames {
            local_var_req_builder = local_var_req_builder.query(&[("maxRefFrames", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_video_bit_depth {
            local_var_req_builder = local_var_req_builder.query(&[("maxVideoBitDepth", &param_value.to_string())]);
        }
        if let Some(ref param_value) = require_avc {
            local_var_req_builder = local_var_req_builder.query(&[("requireAvc", &param_value.to_string())]);
        }
        if let Some(ref param_value) = de_interlace {
            local_var_req_builder = local_var_req_builder.query(&[("deInterlace", &param_value.to_string())]);
        }
        if let Some(ref param_value) = require_non_anamorphic {
            local_var_req_builder = local_var_req_builder.query(&[("requireNonAnamorphic", &param_value.to_string())]);
        }
        if let Some(ref param_value) = transcoding_max_audio_channels {
            local_var_req_builder = local_var_req_builder.query(&[("transcodingMaxAudioChannels", &param_value.to_string())]);
        }
        if let Some(ref param_value) = cpu_core_limit {
            local_var_req_builder = local_var_req_builder.query(&[("cpuCoreLimit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = live_stream_id {
            local_var_req_builder = local_var_req_builder.query(&[("liveStreamId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = enable_mpegts_m2_ts_mode {
            local_var_req_builder = local_var_req_builder.query(&[("enableMpegtsM2TsMode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = video_codec {
            local_var_req_builder = local_var_req_builder.query(&[("videoCodec", &param_value.to_string())]);
        }
        if let Some(ref param_value) = subtitle_codec {
            local_var_req_builder = local_var_req_builder.query(&[("subtitleCodec", &param_value.to_string())]);
        }
        if let Some(ref param_value) = transcode_reasons {
            local_var_req_builder = local_var_req_builder.query(&[("transcodeReasons", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_stream_index {
            local_var_req_builder = local_var_req_builder.query(&[("audioStreamIndex", &param_value.to_string())]);
        }
        if let Some(ref param_value) = video_stream_index {
            local_var_req_builder = local_var_req_builder.query(&[("videoStreamIndex", &param_value.to_string())]);
        }
        if let Some(ref param_value) = context {
            local_var_req_builder = local_var_req_builder.query(&[("context", &param_value.to_string())]);
        }
        if let Some(ref param_value) = stream_options {
            let params = crate::apis::parse_deep_object("streamOptions", &serde_json::to_value(param_value)?);
            local_var_req_builder = local_var_req_builder.query(&params);
        }
        if let Some(ref param_value) = enable_audio_vbr_encoding {
            local_var_req_builder = local_var_req_builder.query(&[("enableAudioVbrEncoding", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `std::path::PathBuf`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `std::path::PathBuf`")))),
            }
        } else {
            let local_var_entity: Option<HeadAudioStreamByContainerError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn head_universal_audio_stream(&self,  params: HeadUniversalAudioStreamParams ) -> Result<std::path::PathBuf, Error<HeadUniversalAudioStreamError>> {
        
        let HeadUniversalAudioStreamParams {
            item_id,
            container,
            media_source_id,
            device_id,
            user_id,
            audio_codec,
            max_audio_channels,
            transcoding_audio_channels,
            max_streaming_bitrate,
            audio_bit_rate,
            start_time_ticks,
            transcoding_container,
            transcoding_protocol,
            max_audio_sample_rate,
            max_audio_bit_depth,
            enable_remote_media,
            enable_audio_vbr_encoding,
            enable_redirection,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Audio/{itemId}/universal", local_var_configuration.base_path, itemId=crate::apis::urlencode(item_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::HEAD, local_var_uri_str.as_str());

        if let Some(ref param_value) = container {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(&param_value.into_iter().map(|p| ("container".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
                _ => local_var_req_builder.query(&[("container", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
            };
        }
        if let Some(ref param_value) = media_source_id {
            local_var_req_builder = local_var_req_builder.query(&[("mediaSourceId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = device_id {
            local_var_req_builder = local_var_req_builder.query(&[("deviceId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = user_id {
            local_var_req_builder = local_var_req_builder.query(&[("userId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_codec {
            local_var_req_builder = local_var_req_builder.query(&[("audioCodec", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_audio_channels {
            local_var_req_builder = local_var_req_builder.query(&[("maxAudioChannels", &param_value.to_string())]);
        }
        if let Some(ref param_value) = transcoding_audio_channels {
            local_var_req_builder = local_var_req_builder.query(&[("transcodingAudioChannels", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_streaming_bitrate {
            local_var_req_builder = local_var_req_builder.query(&[("maxStreamingBitrate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_bit_rate {
            local_var_req_builder = local_var_req_builder.query(&[("audioBitRate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = start_time_ticks {
            local_var_req_builder = local_var_req_builder.query(&[("startTimeTicks", &param_value.to_string())]);
        }
        if let Some(ref param_value) = transcoding_container {
            local_var_req_builder = local_var_req_builder.query(&[("transcodingContainer", &param_value.to_string())]);
        }
        if let Some(ref param_value) = transcoding_protocol {
            local_var_req_builder = local_var_req_builder.query(&[("transcodingProtocol", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_audio_sample_rate {
            local_var_req_builder = local_var_req_builder.query(&[("maxAudioSampleRate", &param_value.to_string())]);
        }
        if let Some(ref param_value) = max_audio_bit_depth {
            local_var_req_builder = local_var_req_builder.query(&[("maxAudioBitDepth", &param_value.to_string())]);
        }
        if let Some(ref param_value) = enable_remote_media {
            local_var_req_builder = local_var_req_builder.query(&[("enableRemoteMedia", &param_value.to_string())]);
        }
        if let Some(ref param_value) = enable_audio_vbr_encoding {
            local_var_req_builder = local_var_req_builder.query(&[("enableAudioVbrEncoding", &param_value.to_string())]);
        }
        if let Some(ref param_value) = enable_redirection {
            local_var_req_builder = local_var_req_builder.query(&[("enableRedirection", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `std::path::PathBuf`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `std::path::PathBuf`")))),
            }
        } else {
            let local_var_entity: Option<HeadUniversalAudioStreamError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

}

/// struct for typed errors of method [`AudioApi::get_audio_stream`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAudioStreamError {
    Status503(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AudioApi::get_audio_stream_by_container`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAudioStreamByContainerError {
    Status503(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AudioApi::get_universal_audio_stream`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetUniversalAudioStreamError {
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AudioApi::head_audio_stream`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum HeadAudioStreamError {
    Status503(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AudioApi::head_audio_stream_by_container`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum HeadAudioStreamByContainerError {
    Status503(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AudioApi::head_universal_audio_stream`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum HeadUniversalAudioStreamError {
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

