/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`close_live_stream`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CloseLiveStreamError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_bitrate_test_bytes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetBitrateTestBytesError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_playback_info`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPlaybackInfoError {
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_posted_playback_info`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPostedPlaybackInfoError {
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`open_live_stream`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OpenLiveStreamError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}


pub async fn close_live_stream(configuration: &configuration::Configuration, live_stream_id: &str) -> Result<(), Error<CloseLiveStreamError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_live_stream_id = live_stream_id;

    let uri_str = format!("{}/LiveStreams/Close", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("liveStreamId", &p_query_live_stream_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<CloseLiveStreamError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_bitrate_test_bytes(configuration: &configuration::Configuration, size: Option<i32>) -> Result<reqwest::Response, Error<GetBitrateTestBytesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_size = size;

    let uri_str = format!("{}/Playback/BitrateTest", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_size {
        req_builder = req_builder.query(&[("size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<GetBitrateTestBytesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_playback_info(configuration: &configuration::Configuration, item_id: &str, user_id: Option<&str>) -> Result<models::PlaybackInfoResponse, Error<GetPlaybackInfoError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_item_id = item_id;
    let p_query_user_id = user_id;

    let uri_str = format!("{}/Items/{itemId}/PlaybackInfo", configuration.base_path, itemId=crate::apis::urlencode(p_path_item_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PlaybackInfoResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PlaybackInfoResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetPlaybackInfoError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// For backwards compatibility parameters can be sent via Query or Body, with Query having higher precedence. Query parameters are obsolete.
pub async fn get_posted_playback_info(configuration: &configuration::Configuration, item_id: &str, user_id: Option<&str>, max_streaming_bitrate: Option<i32>, start_time_ticks: Option<i64>, audio_stream_index: Option<i32>, subtitle_stream_index: Option<i32>, max_audio_channels: Option<i32>, media_source_id: Option<&str>, live_stream_id: Option<&str>, auto_open_live_stream: Option<bool>, enable_direct_play: Option<bool>, enable_direct_stream: Option<bool>, enable_transcoding: Option<bool>, allow_video_stream_copy: Option<bool>, allow_audio_stream_copy: Option<bool>, playback_info_dto: Option<models::PlaybackInfoDto>) -> Result<models::PlaybackInfoResponse, Error<GetPostedPlaybackInfoError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_item_id = item_id;
    let p_query_user_id = user_id;
    let p_query_max_streaming_bitrate = max_streaming_bitrate;
    let p_query_start_time_ticks = start_time_ticks;
    let p_query_audio_stream_index = audio_stream_index;
    let p_query_subtitle_stream_index = subtitle_stream_index;
    let p_query_max_audio_channels = max_audio_channels;
    let p_query_media_source_id = media_source_id;
    let p_query_live_stream_id = live_stream_id;
    let p_query_auto_open_live_stream = auto_open_live_stream;
    let p_query_enable_direct_play = enable_direct_play;
    let p_query_enable_direct_stream = enable_direct_stream;
    let p_query_enable_transcoding = enable_transcoding;
    let p_query_allow_video_stream_copy = allow_video_stream_copy;
    let p_query_allow_audio_stream_copy = allow_audio_stream_copy;
    let p_body_playback_info_dto = playback_info_dto;

    let uri_str = format!("{}/Items/{itemId}/PlaybackInfo", configuration.base_path, itemId=crate::apis::urlencode(p_path_item_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_query_user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_max_streaming_bitrate {
        req_builder = req_builder.query(&[("maxStreamingBitrate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_start_time_ticks {
        req_builder = req_builder.query(&[("startTimeTicks", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_audio_stream_index {
        req_builder = req_builder.query(&[("audioStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_subtitle_stream_index {
        req_builder = req_builder.query(&[("subtitleStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_max_audio_channels {
        req_builder = req_builder.query(&[("maxAudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_media_source_id {
        req_builder = req_builder.query(&[("mediaSourceId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_live_stream_id {
        req_builder = req_builder.query(&[("liveStreamId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_auto_open_live_stream {
        req_builder = req_builder.query(&[("autoOpenLiveStream", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_enable_direct_play {
        req_builder = req_builder.query(&[("enableDirectPlay", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_enable_direct_stream {
        req_builder = req_builder.query(&[("enableDirectStream", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_enable_transcoding {
        req_builder = req_builder.query(&[("enableTranscoding", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_allow_video_stream_copy {
        req_builder = req_builder.query(&[("allowVideoStreamCopy", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_allow_audio_stream_copy {
        req_builder = req_builder.query(&[("allowAudioStreamCopy", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&p_body_playback_info_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PlaybackInfoResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PlaybackInfoResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetPostedPlaybackInfoError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn open_live_stream(configuration: &configuration::Configuration, open_token: Option<&str>, user_id: Option<&str>, play_session_id: Option<&str>, max_streaming_bitrate: Option<i32>, start_time_ticks: Option<i64>, audio_stream_index: Option<i32>, subtitle_stream_index: Option<i32>, max_audio_channels: Option<i32>, item_id: Option<&str>, enable_direct_play: Option<bool>, enable_direct_stream: Option<bool>, always_burn_in_subtitle_when_transcoding: Option<bool>, open_live_stream_dto: Option<models::OpenLiveStreamDto>) -> Result<models::LiveStreamResponse, Error<OpenLiveStreamError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_open_token = open_token;
    let p_query_user_id = user_id;
    let p_query_play_session_id = play_session_id;
    let p_query_max_streaming_bitrate = max_streaming_bitrate;
    let p_query_start_time_ticks = start_time_ticks;
    let p_query_audio_stream_index = audio_stream_index;
    let p_query_subtitle_stream_index = subtitle_stream_index;
    let p_query_max_audio_channels = max_audio_channels;
    let p_query_item_id = item_id;
    let p_query_enable_direct_play = enable_direct_play;
    let p_query_enable_direct_stream = enable_direct_stream;
    let p_query_always_burn_in_subtitle_when_transcoding = always_burn_in_subtitle_when_transcoding;
    let p_body_open_live_stream_dto = open_live_stream_dto;

    let uri_str = format!("{}/LiveStreams/Open", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_query_open_token {
        req_builder = req_builder.query(&[("openToken", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_play_session_id {
        req_builder = req_builder.query(&[("playSessionId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_max_streaming_bitrate {
        req_builder = req_builder.query(&[("maxStreamingBitrate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_start_time_ticks {
        req_builder = req_builder.query(&[("startTimeTicks", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_audio_stream_index {
        req_builder = req_builder.query(&[("audioStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_subtitle_stream_index {
        req_builder = req_builder.query(&[("subtitleStreamIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_max_audio_channels {
        req_builder = req_builder.query(&[("maxAudioChannels", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_item_id {
        req_builder = req_builder.query(&[("itemId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_enable_direct_play {
        req_builder = req_builder.query(&[("enableDirectPlay", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_enable_direct_stream {
        req_builder = req_builder.query(&[("enableDirectStream", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_always_burn_in_subtitle_when_transcoding {
        req_builder = req_builder.query(&[("alwaysBurnInSubtitleWhenTranscoding", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&p_body_open_live_stream_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LiveStreamResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LiveStreamResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<OpenLiveStreamError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

