/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`add_item_to_playlist`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddItemToPlaylistError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_playlist`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreatePlaylistError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_playlist`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPlaylistError {
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_playlist_items`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPlaylistItemsError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_playlist_user`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPlaylistUserError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_playlist_users`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPlaylistUsersError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`move_item`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MoveItemError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`remove_item_from_playlist`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RemoveItemFromPlaylistError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`remove_user_from_playlist`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RemoveUserFromPlaylistError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status401(),
    Status503(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_playlist`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdatePlaylistError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_playlist_user`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdatePlaylistUserError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    UnknownValue(serde_json::Value),
}


pub async fn add_item_to_playlist(configuration: &configuration::Configuration, playlist_id: &str, ids: Option<Vec<uuid::Uuid>>, position: Option<i32>, user_id: Option<&str>) -> Result<(), Error<AddItemToPlaylistError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_playlist_id = playlist_id;
    let p_query_ids = ids;
    let p_query_position = position;
    let p_query_user_id = user_id;

    let uri_str = format!("{}/Playlists/{playlistId}/Items", configuration.base_path, playlistId=crate::apis::urlencode(p_path_playlist_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_query_ids {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("ids".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("ids", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_position {
        req_builder = req_builder.query(&[("position", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AddItemToPlaylistError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// For backwards compatibility parameters can be sent via Query or Body, with Query having higher precedence. Query parameters are obsolete.
pub async fn create_playlist(configuration: &configuration::Configuration, name: Option<&str>, ids: Option<Vec<uuid::Uuid>>, user_id: Option<&str>, media_type: Option<&str>, create_playlist_dto: Option<models::CreatePlaylistDto>) -> Result<models::PlaylistCreationResult, Error<CreatePlaylistError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_name = name;
    let p_query_ids = ids;
    let p_query_user_id = user_id;
    let p_query_media_type = media_type;
    let p_body_create_playlist_dto = create_playlist_dto;

    let uri_str = format!("{}/Playlists", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_query_name {
        req_builder = req_builder.query(&[("name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_ids {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("ids".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("ids", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_media_type {
        req_builder = req_builder.query(&[("mediaType", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&p_body_create_playlist_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PlaylistCreationResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PlaylistCreationResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreatePlaylistError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_playlist(configuration: &configuration::Configuration, playlist_id: &str) -> Result<models::PlaylistDto, Error<GetPlaylistError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_playlist_id = playlist_id;

    let uri_str = format!("{}/Playlists/{playlistId}", configuration.base_path, playlistId=crate::apis::urlencode(p_path_playlist_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PlaylistDto`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PlaylistDto`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetPlaylistError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_playlist_items(configuration: &configuration::Configuration, playlist_id: &str, user_id: Option<&str>, start_index: Option<i32>, limit: Option<i32>, fields: Option<Vec<models::ItemFields>>, enable_images: Option<bool>, enable_user_data: Option<bool>, image_type_limit: Option<i32>, enable_image_types: Option<Vec<models::ImageType>>) -> Result<models::BaseItemDtoQueryResult, Error<GetPlaylistItemsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_playlist_id = playlist_id;
    let p_query_user_id = user_id;
    let p_query_start_index = start_index;
    let p_query_limit = limit;
    let p_query_fields = fields;
    let p_query_enable_images = enable_images;
    let p_query_enable_user_data = enable_user_data;
    let p_query_image_type_limit = image_type_limit;
    let p_query_enable_image_types = enable_image_types;

    let uri_str = format!("{}/Playlists/{playlistId}/Items", configuration.base_path, playlistId=crate::apis::urlencode(p_path_playlist_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_start_index {
        req_builder = req_builder.query(&[("startIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_fields {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("fields".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("fields", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_enable_images {
        req_builder = req_builder.query(&[("enableImages", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_enable_user_data {
        req_builder = req_builder.query(&[("enableUserData", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_image_type_limit {
        req_builder = req_builder.query(&[("imageTypeLimit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_enable_image_types {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("enableImageTypes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("enableImageTypes", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BaseItemDtoQueryResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BaseItemDtoQueryResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetPlaylistItemsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_playlist_user(configuration: &configuration::Configuration, playlist_id: &str, user_id: &str) -> Result<models::PlaylistUserPermissions, Error<GetPlaylistUserError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_playlist_id = playlist_id;
    let p_path_user_id = user_id;

    let uri_str = format!("{}/Playlists/{playlistId}/Users/{userId}", configuration.base_path, playlistId=crate::apis::urlencode(p_path_playlist_id), userId=crate::apis::urlencode(p_path_user_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PlaylistUserPermissions`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PlaylistUserPermissions`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetPlaylistUserError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_playlist_users(configuration: &configuration::Configuration, playlist_id: &str) -> Result<Vec<models::PlaylistUserPermissions>, Error<GetPlaylistUsersError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_playlist_id = playlist_id;

    let uri_str = format!("{}/Playlists/{playlistId}/Users", configuration.base_path, playlistId=crate::apis::urlencode(p_path_playlist_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::PlaylistUserPermissions&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::PlaylistUserPermissions&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetPlaylistUsersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn move_item(configuration: &configuration::Configuration, playlist_id: &str, item_id: &str, new_index: i32) -> Result<(), Error<MoveItemError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_playlist_id = playlist_id;
    let p_path_item_id = item_id;
    let p_path_new_index = new_index;

    let uri_str = format!("{}/Playlists/{playlistId}/Items/{itemId}/Move/{newIndex}", configuration.base_path, playlistId=crate::apis::urlencode(p_path_playlist_id), itemId=crate::apis::urlencode(p_path_item_id), newIndex=p_path_new_index);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<MoveItemError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn remove_item_from_playlist(configuration: &configuration::Configuration, playlist_id: &str, entry_ids: Option<Vec<String>>) -> Result<(), Error<RemoveItemFromPlaylistError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_playlist_id = playlist_id;
    let p_query_entry_ids = entry_ids;

    let uri_str = format!("{}/Playlists/{playlistId}/Items", configuration.base_path, playlistId=crate::apis::urlencode(p_path_playlist_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref param_value) = p_query_entry_ids {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("entryIds".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("entryIds", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RemoveItemFromPlaylistError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn remove_user_from_playlist(configuration: &configuration::Configuration, playlist_id: &str, user_id: &str) -> Result<(), Error<RemoveUserFromPlaylistError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_playlist_id = playlist_id;
    let p_path_user_id = user_id;

    let uri_str = format!("{}/Playlists/{playlistId}/Users/{userId}", configuration.base_path, playlistId=crate::apis::urlencode(p_path_playlist_id), userId=crate::apis::urlencode(p_path_user_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RemoveUserFromPlaylistError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn update_playlist(configuration: &configuration::Configuration, playlist_id: &str, update_playlist_dto: models::UpdatePlaylistDto) -> Result<(), Error<UpdatePlaylistError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_playlist_id = playlist_id;
    let p_body_update_playlist_dto = update_playlist_dto;

    let uri_str = format!("{}/Playlists/{playlistId}", configuration.base_path, playlistId=crate::apis::urlencode(p_path_playlist_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&p_body_update_playlist_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdatePlaylistError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn update_playlist_user(configuration: &configuration::Configuration, playlist_id: &str, user_id: &str, update_playlist_user_dto: models::UpdatePlaylistUserDto) -> Result<(), Error<UpdatePlaylistUserError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_playlist_id = playlist_id;
    let p_path_user_id = user_id;
    let p_body_update_playlist_user_dto = update_playlist_user_dto;

    let uri_str = format!("{}/Playlists/{playlistId}/Users/{userId}", configuration.base_path, playlistId=crate::apis::urlencode(p_path_playlist_id), userId=crate::apis::urlencode(p_path_user_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&p_body_update_playlist_user_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdatePlaylistUserError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

