/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_search_hints`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSearchHintsError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}


pub async fn get_search_hints(configuration: &configuration::Configuration, search_term: &str, start_index: Option<i32>, limit: Option<i32>, user_id: Option<&str>, include_item_types: Option<Vec<models::BaseItemKind>>, exclude_item_types: Option<Vec<models::BaseItemKind>>, media_types: Option<Vec<models::MediaType>>, parent_id: Option<&str>, is_movie: Option<bool>, is_series: Option<bool>, is_news: Option<bool>, is_kids: Option<bool>, is_sports: Option<bool>, include_people: Option<bool>, include_media: Option<bool>, include_genres: Option<bool>, include_studios: Option<bool>, include_artists: Option<bool>) -> Result<models::SearchHintResult, Error<GetSearchHintsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_search_term = search_term;
    let p_query_start_index = start_index;
    let p_query_limit = limit;
    let p_query_user_id = user_id;
    let p_query_include_item_types = include_item_types;
    let p_query_exclude_item_types = exclude_item_types;
    let p_query_media_types = media_types;
    let p_query_parent_id = parent_id;
    let p_query_is_movie = is_movie;
    let p_query_is_series = is_series;
    let p_query_is_news = is_news;
    let p_query_is_kids = is_kids;
    let p_query_is_sports = is_sports;
    let p_query_include_people = include_people;
    let p_query_include_media = include_media;
    let p_query_include_genres = include_genres;
    let p_query_include_studios = include_studios;
    let p_query_include_artists = include_artists;

    let uri_str = format!("{}/Search/Hints", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_start_index {
        req_builder = req_builder.query(&[("startIndex", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_user_id {
        req_builder = req_builder.query(&[("userId", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("searchTerm", &p_query_search_term.to_string())]);
    if let Some(ref param_value) = p_query_include_item_types {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("includeItemTypes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("includeItemTypes", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_exclude_item_types {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("excludeItemTypes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("excludeItemTypes", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_media_types {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("mediaTypes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("mediaTypes", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_parent_id {
        req_builder = req_builder.query(&[("parentId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_is_movie {
        req_builder = req_builder.query(&[("isMovie", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_is_series {
        req_builder = req_builder.query(&[("isSeries", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_is_news {
        req_builder = req_builder.query(&[("isNews", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_is_kids {
        req_builder = req_builder.query(&[("isKids", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_is_sports {
        req_builder = req_builder.query(&[("isSports", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_include_people {
        req_builder = req_builder.query(&[("includePeople", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_include_media {
        req_builder = req_builder.query(&[("includeMedia", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_include_genres {
        req_builder = req_builder.query(&[("includeGenres", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_include_studios {
        req_builder = req_builder.query(&[("includeStudios", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_include_artists {
        req_builder = req_builder.query(&[("includeArtists", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SearchHintResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SearchHintResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSearchHintsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

