/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use async_trait::async_trait;
use reqwest;
use std::sync::Arc;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};
use crate::apis::ContentType;

#[async_trait]
pub trait SessionApi: Send + Sync {

    /// POST /Sessions/{sessionId}/User/{userId}
    ///
    /// 
    async fn add_user_to_session(&self,  params: AddUserToSessionParams ) -> Result<(), Error<AddUserToSessionError>>;

    /// POST /Sessions/{sessionId}/Viewing
    ///
    /// 
    async fn display_content(&self,  params: DisplayContentParams ) -> Result<(), Error<DisplayContentError>>;

    /// GET /Sessions
    ///
    /// 
    async fn get_sessions(&self,  params: GetSessionsParams ) -> Result<Vec<models::SessionInfoDto>, Error<GetSessionsError>>;

    /// POST /Sessions/Playing/Ping
    ///
    /// 
    async fn ping_playback_session(&self,  params: PingPlaybackSessionParams ) -> Result<(), Error<PingPlaybackSessionError>>;

    /// POST /Sessions/{sessionId}/Playing
    ///
    /// 
    async fn play(&self,  params: PlayParams ) -> Result<(), Error<PlayError>>;

    /// POST /Sessions/Capabilities
    ///
    /// 
    async fn post_capabilities(&self,  params: PostCapabilitiesParams ) -> Result<(), Error<PostCapabilitiesError>>;

    /// POST /Sessions/Capabilities/Full
    ///
    /// 
    async fn post_full_capabilities(&self,  params: PostFullCapabilitiesParams ) -> Result<(), Error<PostFullCapabilitiesError>>;

    /// DELETE /Sessions/{sessionId}/User/{userId}
    ///
    /// 
    async fn remove_user_from_session(&self,  params: RemoveUserFromSessionParams ) -> Result<(), Error<RemoveUserFromSessionError>>;

    /// POST /Sessions/Playing/Progress
    ///
    /// 
    async fn report_playback_progress(&self,  params: ReportPlaybackProgressParams ) -> Result<(), Error<ReportPlaybackProgressError>>;

    /// POST /Sessions/Playing
    ///
    /// 
    async fn report_playback_start(&self,  params: ReportPlaybackStartParams ) -> Result<(), Error<ReportPlaybackStartError>>;

    /// POST /Sessions/Playing/Stopped
    ///
    /// 
    async fn report_playback_stopped(&self,  params: ReportPlaybackStoppedParams ) -> Result<(), Error<ReportPlaybackStoppedError>>;

    /// POST /Sessions/Logout
    ///
    /// 
    async fn report_session_ended(&self, ) -> Result<(), Error<ReportSessionEndedError>>;

    /// POST /Sessions/Viewing
    ///
    /// 
    async fn report_viewing(&self,  params: ReportViewingParams ) -> Result<(), Error<ReportViewingError>>;

    /// POST /Sessions/{sessionId}/Command
    ///
    /// 
    async fn send_full_general_command(&self,  params: SendFullGeneralCommandParams ) -> Result<(), Error<SendFullGeneralCommandError>>;

    /// POST /Sessions/{sessionId}/Command/{command}
    ///
    /// 
    async fn send_general_command(&self,  params: SendGeneralCommandParams ) -> Result<(), Error<SendGeneralCommandError>>;

    /// POST /Sessions/{sessionId}/Message
    ///
    /// 
    async fn send_message_command(&self,  params: SendMessageCommandParams ) -> Result<(), Error<SendMessageCommandError>>;

    /// POST /Sessions/{sessionId}/Playing/{command}
    ///
    /// 
    async fn send_playstate_command(&self,  params: SendPlaystateCommandParams ) -> Result<(), Error<SendPlaystateCommandError>>;

    /// POST /Sessions/{sessionId}/System/{command}
    ///
    /// 
    async fn send_system_command(&self,  params: SendSystemCommandParams ) -> Result<(), Error<SendSystemCommandError>>;
}

pub struct SessionApiClient {
    configuration: Arc<configuration::Configuration>
}

impl SessionApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}


/// struct for passing parameters to the method [`SessionApi::add_user_to_session`]
#[derive(Clone, Debug)]
pub struct AddUserToSessionParams {
    /// The session id.
    pub session_id: String,
    /// The user id.
    pub user_id: String
}

/// struct for passing parameters to the method [`SessionApi::display_content`]
#[derive(Clone, Debug)]
pub struct DisplayContentParams {
    /// The session Id.
    pub session_id: String,
    /// The type of item to browse to.
    pub item_type: String,
    /// The Id of the item.
    pub item_id: String,
    /// The name of the item.
    pub item_name: String
}

/// struct for passing parameters to the method [`SessionApi::get_sessions`]
#[derive(Clone, Debug)]
pub struct GetSessionsParams {
    /// Filter by sessions that a given user is allowed to remote control.
    pub controllable_by_user_id: Option<String>,
    /// Filter by device Id.
    pub device_id: Option<String>,
    /// Optional. Filter by sessions that were active in the last n seconds.
    pub active_within_seconds: Option<i32>
}

/// struct for passing parameters to the method [`SessionApi::ping_playback_session`]
#[derive(Clone, Debug)]
pub struct PingPlaybackSessionParams {
    /// Playback session id.
    pub play_session_id: String
}

/// struct for passing parameters to the method [`SessionApi::play`]
#[derive(Clone, Debug)]
pub struct PlayParams {
    /// The session id.
    pub session_id: String,
    /// The type of play command to issue (PlayNow, PlayNext, PlayLast). Clients who have not yet implemented play next and play last may play now.
    pub play_command: String,
    /// The ids of the items to play, comma delimited.
    pub item_ids: Vec<uuid::Uuid>,
    /// The starting position of the first item.
    pub start_position_ticks: Option<i64>,
    /// Optional. The media source id.
    pub media_source_id: Option<String>,
    /// Optional. The index of the audio stream to play.
    pub audio_stream_index: Option<i32>,
    /// Optional. The index of the subtitle stream to play.
    pub subtitle_stream_index: Option<i32>,
    /// Optional. The start index.
    pub start_index: Option<i32>
}

/// struct for passing parameters to the method [`SessionApi::post_capabilities`]
#[derive(Clone, Debug)]
pub struct PostCapabilitiesParams {
    /// The session id.
    pub id: Option<String>,
    /// A list of playable media types, comma delimited. Audio, Video, Book, Photo.
    pub playable_media_types: Option<Vec<models::MediaType>>,
    /// A list of supported remote control commands, comma delimited.
    pub supported_commands: Option<Vec<models::GeneralCommandType>>,
    /// Determines whether media can be played remotely..
    pub supports_media_control: Option<bool>,
    /// Determines whether the device supports a unique identifier.
    pub supports_persistent_identifier: Option<bool>
}

/// struct for passing parameters to the method [`SessionApi::post_full_capabilities`]
#[derive(Clone, Debug)]
pub struct PostFullCapabilitiesParams {
    /// The MediaBrowser.Model.Session.ClientCapabilities.
    pub client_capabilities_dto: models::ClientCapabilitiesDto,
    /// The session id.
    pub id: Option<String>
}

/// struct for passing parameters to the method [`SessionApi::remove_user_from_session`]
#[derive(Clone, Debug)]
pub struct RemoveUserFromSessionParams {
    /// The session id.
    pub session_id: String,
    /// The user id.
    pub user_id: String
}

/// struct for passing parameters to the method [`SessionApi::report_playback_progress`]
#[derive(Clone, Debug)]
pub struct ReportPlaybackProgressParams {
    /// The playback progress info.
    pub playback_progress_info: Option<models::PlaybackProgressInfo>
}

/// struct for passing parameters to the method [`SessionApi::report_playback_start`]
#[derive(Clone, Debug)]
pub struct ReportPlaybackStartParams {
    /// The playback start info.
    pub playback_start_info: Option<models::PlaybackStartInfo>
}

/// struct for passing parameters to the method [`SessionApi::report_playback_stopped`]
#[derive(Clone, Debug)]
pub struct ReportPlaybackStoppedParams {
    /// The playback stop info.
    pub playback_stop_info: Option<models::PlaybackStopInfo>
}

/// struct for passing parameters to the method [`SessionApi::report_viewing`]
#[derive(Clone, Debug)]
pub struct ReportViewingParams {
    /// The item id.
    pub item_id: String,
    /// The session id.
    pub session_id: Option<String>
}

/// struct for passing parameters to the method [`SessionApi::send_full_general_command`]
#[derive(Clone, Debug)]
pub struct SendFullGeneralCommandParams {
    /// The session id.
    pub session_id: String,
    /// The MediaBrowser.Model.Session.GeneralCommand.
    pub general_command: models::GeneralCommand
}

/// struct for passing parameters to the method [`SessionApi::send_general_command`]
#[derive(Clone, Debug)]
pub struct SendGeneralCommandParams {
    /// The session id.
    pub session_id: String,
    /// The command to send.
    pub command: String
}

/// struct for passing parameters to the method [`SessionApi::send_message_command`]
#[derive(Clone, Debug)]
pub struct SendMessageCommandParams {
    /// The session id.
    pub session_id: String,
    /// The MediaBrowser.Model.Session.MessageCommand object containing Header, Message Text, and TimeoutMs.
    pub message_command: models::MessageCommand
}

/// struct for passing parameters to the method [`SessionApi::send_playstate_command`]
#[derive(Clone, Debug)]
pub struct SendPlaystateCommandParams {
    /// The session id.
    pub session_id: String,
    /// The MediaBrowser.Model.Session.PlaystateCommand.
    pub command: String,
    /// The optional position ticks.
    pub seek_position_ticks: Option<i64>,
    /// The optional controlling user id.
    pub controlling_user_id: Option<String>
}

/// struct for passing parameters to the method [`SessionApi::send_system_command`]
#[derive(Clone, Debug)]
pub struct SendSystemCommandParams {
    /// The session id.
    pub session_id: String,
    /// The command to send.
    pub command: String
}


#[async_trait]
impl SessionApi for SessionApiClient {
    async fn add_user_to_session(&self,  params: AddUserToSessionParams ) -> Result<(), Error<AddUserToSessionError>> {
        
        let AddUserToSessionParams {
            session_id,
            user_id,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions/{sessionId}/User/{userId}", local_var_configuration.base_path, sessionId=crate::apis::urlencode(session_id), userId=crate::apis::urlencode(user_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<AddUserToSessionError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn display_content(&self,  params: DisplayContentParams ) -> Result<(), Error<DisplayContentError>> {
        
        let DisplayContentParams {
            session_id,
            item_type,
            item_id,
            item_name,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions/{sessionId}/Viewing", local_var_configuration.base_path, sessionId=crate::apis::urlencode(session_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.query(&[("itemType", &item_type.to_string())]);
        local_var_req_builder = local_var_req_builder.query(&[("itemId", &item_id.to_string())]);
        local_var_req_builder = local_var_req_builder.query(&[("itemName", &item_name.to_string())]);
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<DisplayContentError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_sessions(&self,  params: GetSessionsParams ) -> Result<Vec<models::SessionInfoDto>, Error<GetSessionsError>> {
        
        let GetSessionsParams {
            controllable_by_user_id,
            device_id,
            active_within_seconds,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = controllable_by_user_id {
            local_var_req_builder = local_var_req_builder.query(&[("controllableByUserId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = device_id {
            local_var_req_builder = local_var_req_builder.query(&[("deviceId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = active_within_seconds {
            local_var_req_builder = local_var_req_builder.query(&[("activeWithinSeconds", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::SessionInfoDto&gt;`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `Vec&lt;models::SessionInfoDto&gt;`")))),
            }
        } else {
            let local_var_entity: Option<GetSessionsError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn ping_playback_session(&self,  params: PingPlaybackSessionParams ) -> Result<(), Error<PingPlaybackSessionError>> {
        
        let PingPlaybackSessionParams {
            play_session_id,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions/Playing/Ping", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.query(&[("playSessionId", &play_session_id.to_string())]);
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<PingPlaybackSessionError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn play(&self,  params: PlayParams ) -> Result<(), Error<PlayError>> {
        
        let PlayParams {
            session_id,
            play_command,
            item_ids,
            start_position_ticks,
            media_source_id,
            audio_stream_index,
            subtitle_stream_index,
            start_index,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions/{sessionId}/Playing", local_var_configuration.base_path, sessionId=crate::apis::urlencode(session_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.query(&[("playCommand", &play_command.to_string())]);
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(&item_ids.into_iter().map(|p| ("itemIds".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => local_var_req_builder.query(&[("itemIds", &item_ids.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
        if let Some(ref param_value) = start_position_ticks {
            local_var_req_builder = local_var_req_builder.query(&[("startPositionTicks", &param_value.to_string())]);
        }
        if let Some(ref param_value) = media_source_id {
            local_var_req_builder = local_var_req_builder.query(&[("mediaSourceId", &param_value.to_string())]);
        }
        if let Some(ref param_value) = audio_stream_index {
            local_var_req_builder = local_var_req_builder.query(&[("audioStreamIndex", &param_value.to_string())]);
        }
        if let Some(ref param_value) = subtitle_stream_index {
            local_var_req_builder = local_var_req_builder.query(&[("subtitleStreamIndex", &param_value.to_string())]);
        }
        if let Some(ref param_value) = start_index {
            local_var_req_builder = local_var_req_builder.query(&[("startIndex", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<PlayError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn post_capabilities(&self,  params: PostCapabilitiesParams ) -> Result<(), Error<PostCapabilitiesError>> {
        
        let PostCapabilitiesParams {
            id,
            playable_media_types,
            supported_commands,
            supports_media_control,
            supports_persistent_identifier,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions/Capabilities", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref param_value) = id {
            local_var_req_builder = local_var_req_builder.query(&[("id", &param_value.to_string())]);
        }
        if let Some(ref param_value) = playable_media_types {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(&param_value.into_iter().map(|p| ("playableMediaTypes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
                _ => local_var_req_builder.query(&[("playableMediaTypes", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
            };
        }
        if let Some(ref param_value) = supported_commands {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(&param_value.into_iter().map(|p| ("supportedCommands".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
                _ => local_var_req_builder.query(&[("supportedCommands", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
            };
        }
        if let Some(ref param_value) = supports_media_control {
            local_var_req_builder = local_var_req_builder.query(&[("supportsMediaControl", &param_value.to_string())]);
        }
        if let Some(ref param_value) = supports_persistent_identifier {
            local_var_req_builder = local_var_req_builder.query(&[("supportsPersistentIdentifier", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<PostCapabilitiesError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn post_full_capabilities(&self,  params: PostFullCapabilitiesParams ) -> Result<(), Error<PostFullCapabilitiesError>> {
        
        let PostFullCapabilitiesParams {
            client_capabilities_dto,
            id,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions/Capabilities/Full", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref param_value) = id {
            local_var_req_builder = local_var_req_builder.query(&[("id", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&client_capabilities_dto);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<PostFullCapabilitiesError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn remove_user_from_session(&self,  params: RemoveUserFromSessionParams ) -> Result<(), Error<RemoveUserFromSessionError>> {
        
        let RemoveUserFromSessionParams {
            session_id,
            user_id,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions/{sessionId}/User/{userId}", local_var_configuration.base_path, sessionId=crate::apis::urlencode(session_id), userId=crate::apis::urlencode(user_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<RemoveUserFromSessionError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn report_playback_progress(&self,  params: ReportPlaybackProgressParams ) -> Result<(), Error<ReportPlaybackProgressError>> {
        
        let ReportPlaybackProgressParams {
            playback_progress_info,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions/Playing/Progress", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&playback_progress_info);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<ReportPlaybackProgressError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn report_playback_start(&self,  params: ReportPlaybackStartParams ) -> Result<(), Error<ReportPlaybackStartError>> {
        
        let ReportPlaybackStartParams {
            playback_start_info,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions/Playing", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&playback_start_info);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<ReportPlaybackStartError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn report_playback_stopped(&self,  params: ReportPlaybackStoppedParams ) -> Result<(), Error<ReportPlaybackStoppedError>> {
        
        let ReportPlaybackStoppedParams {
            playback_stop_info,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions/Playing/Stopped", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&playback_stop_info);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<ReportPlaybackStoppedError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn report_session_ended(&self, ) -> Result<(), Error<ReportSessionEndedError>> {
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions/Logout", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<ReportSessionEndedError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn report_viewing(&self,  params: ReportViewingParams ) -> Result<(), Error<ReportViewingError>> {
        
        let ReportViewingParams {
            item_id,
            session_id,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions/Viewing", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref param_value) = session_id {
            local_var_req_builder = local_var_req_builder.query(&[("sessionId", &param_value.to_string())]);
        }
        local_var_req_builder = local_var_req_builder.query(&[("itemId", &item_id.to_string())]);
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<ReportViewingError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn send_full_general_command(&self,  params: SendFullGeneralCommandParams ) -> Result<(), Error<SendFullGeneralCommandError>> {
        
        let SendFullGeneralCommandParams {
            session_id,
            general_command,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions/{sessionId}/Command", local_var_configuration.base_path, sessionId=crate::apis::urlencode(session_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&general_command);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<SendFullGeneralCommandError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn send_general_command(&self,  params: SendGeneralCommandParams ) -> Result<(), Error<SendGeneralCommandError>> {
        
        let SendGeneralCommandParams {
            session_id,
            command,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions/{sessionId}/Command/{command}", local_var_configuration.base_path, sessionId=crate::apis::urlencode(session_id), command=crate::apis::urlencode(command));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<SendGeneralCommandError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn send_message_command(&self,  params: SendMessageCommandParams ) -> Result<(), Error<SendMessageCommandError>> {
        
        let SendMessageCommandParams {
            session_id,
            message_command,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions/{sessionId}/Message", local_var_configuration.base_path, sessionId=crate::apis::urlencode(session_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&message_command);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<SendMessageCommandError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn send_playstate_command(&self,  params: SendPlaystateCommandParams ) -> Result<(), Error<SendPlaystateCommandError>> {
        
        let SendPlaystateCommandParams {
            session_id,
            command,
            seek_position_ticks,
            controlling_user_id,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions/{sessionId}/Playing/{command}", local_var_configuration.base_path, sessionId=crate::apis::urlencode(session_id), command=crate::apis::urlencode(command));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref param_value) = seek_position_ticks {
            local_var_req_builder = local_var_req_builder.query(&[("seekPositionTicks", &param_value.to_string())]);
        }
        if let Some(ref param_value) = controlling_user_id {
            local_var_req_builder = local_var_req_builder.query(&[("controllingUserId", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<SendPlaystateCommandError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn send_system_command(&self,  params: SendSystemCommandParams ) -> Result<(), Error<SendSystemCommandError>> {
        
        let SendSystemCommandParams {
            session_id,
            command,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/Sessions/{sessionId}/System/{command}", local_var_configuration.base_path, sessionId=crate::apis::urlencode(session_id), command=crate::apis::urlencode(command));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<SendSystemCommandError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

}

/// struct for typed errors of method [`SessionApi::add_user_to_session`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddUserToSessionError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`SessionApi::display_content`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DisplayContentError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`SessionApi::get_sessions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSessionsError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`SessionApi::ping_playback_session`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PingPlaybackSessionError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`SessionApi::play`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PlayError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`SessionApi::post_capabilities`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostCapabilitiesError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`SessionApi::post_full_capabilities`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostFullCapabilitiesError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`SessionApi::remove_user_from_session`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RemoveUserFromSessionError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`SessionApi::report_playback_progress`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReportPlaybackProgressError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`SessionApi::report_playback_start`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReportPlaybackStartError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`SessionApi::report_playback_stopped`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReportPlaybackStoppedError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`SessionApi::report_session_ended`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReportSessionEndedError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`SessionApi::report_viewing`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReportViewingError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`SessionApi::send_full_general_command`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SendFullGeneralCommandError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`SessionApi::send_general_command`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SendGeneralCommandError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`SessionApi::send_message_command`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SendMessageCommandError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`SessionApi::send_playstate_command`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SendPlaystateCommandError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`SessionApi::send_system_command`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SendSystemCommandError {
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

