/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_trickplay_hls_playlist`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTrickplayHlsPlaylistError {
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_trickplay_tile_image`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTrickplayTileImageError {
    Status404(models::ProblemDetails),
    Status503(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}


pub async fn get_trickplay_hls_playlist(configuration: &configuration::Configuration, item_id: &str, width: i32, media_source_id: Option<&str>) -> Result<reqwest::Response, Error<GetTrickplayHlsPlaylistError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_item_id = item_id;
    let p_path_width = width;
    let p_query_media_source_id = media_source_id;

    let uri_str = format!("{}/Videos/{itemId}/Trickplay/{width}/tiles.m3u8", configuration.base_path, itemId=crate::apis::urlencode(p_path_item_id), width=p_path_width);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_media_source_id {
        req_builder = req_builder.query(&[("mediaSourceId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<GetTrickplayHlsPlaylistError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_trickplay_tile_image(configuration: &configuration::Configuration, item_id: &str, width: i32, index: i32, media_source_id: Option<&str>) -> Result<reqwest::Response, Error<GetTrickplayTileImageError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_item_id = item_id;
    let p_path_width = width;
    let p_path_index = index;
    let p_query_media_source_id = media_source_id;

    let uri_str = format!("{}/Videos/{itemId}/Trickplay/{width}/{index}.jpg", configuration.base_path, itemId=crate::apis::urlencode(p_path_item_id), width=p_path_width, index=p_path_index);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_media_source_id {
        req_builder = req_builder.query(&[("mediaSourceId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<GetTrickplayTileImageError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

